toss/es-toolkit

src/array/chunk.ts

```tsx
for (let index = 0; index < chunkLength; index++) {
const start = index * size;
const end = start + size;
result[index] = arr.slice( start, end);
}
```
```tsx
for (let index = 0; index < chunkLength; index++) {
const start = index * size;
const end = start + size;
result[index] = arr.slice(start, end); // (*)
}
```

style(chunk): Delete unnecessary white space

---

src/array/difference.ts

The es-toolkit's `difference` function becomes slower compared to lodash's `difference` as the array size increases.
Therefore, I have modified the `difference` function in es-toolkit so that it performs faster even as the array size increases.
I have reduced the time complexity from O(n*m) to O(n+m).
firstArr's size : 10
secondArr's size : 5
firstArr's size : 500
secondArr's size : 250
firstArr's size : 10
secondArr's size : 5
firstArr's size : 500
secondArr's size : 250
firstArr's size : 10
secondArr's size : 5
firstArr's size : 500
secondArr's size : 250
firstArr's size : 10,000
secondArr's size : 5,000

perf(difference): Optimize `difference`

---

src/array/differenceBy.ts

The es-toolkit's `differenceBy` function becomes slower compared to lodash's `differenceBy` as the array size increases.
Therefore, I have modified the `differenceBy` function in es-toolkit so that it performs faster even as the array size increases.
I have reduced the time complexity from O(n*m) to O(n+m).
firstArr's size : 3
secondArr's size : 1
mapper: Math.floor
firstArr's size : 500
secondArr's size : 250
mapper: Math.floor
firstArr's size : 3
secondArr's size : 1
mapper: Math.floor
firstArr's size : 500
secondArr's size : 250
mapper: Math.floor
firstArr's size : 3
secondArr's size : 1
mapper: Math.floor
firstArr's size : 500
secondArr's size : 250
mapper: Math.floor
firstArr's size : 10,000
secondArr's size : 5,000
mapper: Math.floor

fix(differenceBy): Make differenceBy fast

---

src/array/shuffle.spec.ts
src/array/shuffle.ts

The previous implementation of the shuffle function modified the original array, which is unintended behavior.
the function now duplicates the array internally before shuffling. This ensures the original array remains unaffected.
- Modify the shuffle function to copy the array before shuffling
- Add a test case to validate the preservation of the original array

fix(shuffle): Ensure shuffle function does not modify original array

---

src/array/differenceWith.ts
src/array/drop.ts
src/array/dropRight.ts
src/array/dropRightWhile.ts
src/array/intersectionWith.ts
src/array/take.ts
src/array/unionBy.ts
src/array/uniq.ts
src/array/uniqBy.ts
src/array/uniqWith.ts
src/array/xorBy.ts
src/array/zipWith.ts
src/math/clamp.ts
src/math/round.ts
src/math/sum.ts
src/object/omit.ts
src/object/pick.ts
src/predicate/isNil.ts
src/predicate/isNull.ts
src/predicate/isUndefined.ts

- Add missing JSDoc type annotations and update incorrect JSDoc type annotations https://github.com/toss/es-toolkit/commit/13688b03d10ce7de0df7f387059c48e505d6306f
- Remove duplicate asterisks from JSDoc annotations https://github.com/toss/es-toolkit/commit/b2dfb336366b65da9d98dbdd4421200dfa5ddccf
- Add missing TypeScript return types https://github.com/toss/es-toolkit/commit/a580c2c5002b12966776895e70de6613cc6d9015

style(*): Fix missing and incorrect JSDoc types

---

src/array/uniqWith.spec.ts
src/array/uniqWith.ts

The `@example` was incorrect and fixed it.
comparator function, if false is returned then add element.
**first iter**
- a: X
- b: 1.2
-> 1.2 < 1 = false, added 1.2
**second iter**
- a: 1.2
- b: 1.5
-> 0.3 < 1 = true, not added 
**third iter**
- a: 1.2
- b: 2.1
-> 0.9 < 1 = true, not added
**fourth iter**
- a: 1.2
- b: 3.2
-> 2.0 < 1 = false, added 3.2
**fifth iter**
- a: 3.2
- b: 5.7
-> 2.5 < 1 = false, added 5.7
**sixth iter**
- a: 5.7
- b: 5.3
-> 0.4 < 1 = true, not added
**seventh iter**
- a: 5.7
- b: 7.19
-> 1.49 < 1 = false, added 7.19
answer: [1.2, 3.2, 5.7, 7.19]

test(uniqWith): Add test cases for uniqWith

---

README-ko_kr.md
README.md

Current README files include links like 
```markdown
English | [한국어](./README-ko_kr.md)
```
And these are not accessible outside github (such as [npm registry](https://www.npmjs.com/package/es-toolkit)). It is because those links are declared as a relative URLs.
So I changed them into absolute URLs:
```markdown
English | [한국어](https://github.com/toss/es-toolkit/blob/main/README-ko_kr.md)
```

docs: Fix broken link from README.md and README-ko_kr.md

---

src/object/omit.spec.ts

**Description:**
Add additional test cases for the omit function to ensure comprehensive coverage
**Changes:**
1. Add test case to check if all keys are omitted:
- Verifies that the function returns an empty object when all keys are omitted.
```
it('should return an empty object if all keys are omitted', () => {
const obj = { a: 1, b: 2, c: 3 };
const result = omit(obj, ['a', 'b', 'c']);
expect(result).toEqual({});
});
```
2. Add test case to check if no keys are omitted:
- Verifies that the function returns the original object when no keys are omitted.
```
it('should return the same object if no keys are omitted', () => {
const obj = { a: 1, b: 2, c: 3 };
const result = omit(obj, []);
expect(result).toEqual({ a: 1, b: 2, c: 3 });
});
```
3. Add test case to check that the original object …

test(omit) : Enhance omit function tests

---

README-ko_kr.md
README.md

docs(README.md): add codecov badge to expose test coverage 100%

---

src/array/intersectionBy.ts

This pull request optimizes the time complexity of the intersectionBy function from O(n*m) to O(n + m). The previous implementation used an array and the includes method, leading to quadratic time complexity due to repeated linear searches. The optimized implementation leverages a Set for constant-time lookups, thus improving the overall performance significantly.
* Benchmark1: small size of array
array 1 size: 10
array 2 size: 5
* Benchmark2: large size of array
array 1 size: 10000
array 2 size: 5000

perf(intersectionBy): optimize time complexity

---

src/array/dropRightWhile.spec.ts
src/array/dropWhile.spec.ts
src/array/dropWhile.ts

Thank you for making this lib!
I found an edge case for `dropWhile` function and I fixed it.

fix(dropWhile): `dropWhile` returns the whole array when every element does not match the predicate

---

docs/ko/reference/object/omitBy.md
docs/ko/reference/object/pickBy.md
docs/reference/object/omitBy.md
docs/reference/object/pickBy.md
src/object/omitBy.ts
src/object/pickBy.ts

Resolves #58.
Previously typescript should assume all `key`s as just `string`.
Now typescript knows specific types of `key`s
And edited existing document as to made changes.
Also, I found that type of `value` had set to `any`, unlike real implementation. So I've fixed that too.
closes #58

fix(pickBy, omitBy): Enforce stricter argument types in `shouldPick` and `shouldOmit`

---

.github/workflows/broken-link-checker.yml

This change fix https://github.com/toss/es-toolkit/actions/workflows/broken-link-checker.yml

ci(broken-link-checker): add default url for schedule

---

docs/ko/reference/predicate/isUndefined.md
docs/reference/predicate/isUndefined.md
src/predicate/isUndefined.spec.ts

I fix documentation and comments related to `isUndefined`.
I applied inline code markdown for `undefined`, `true`, and `false`.
I think this will improve readability.
I changed `null[]` to `undefined[]`.
**AS-IS**
```ts
// Here the type of result should be `null[]`.
expect(result).toStrictEqual([undefined]);
```
**TO-BE**
```ts
// Here the type of result should be `undefined[]`.
expect(result).toStrictEqual([undefined]);
```

docs(isUndefined): Polish document styles and fix incorrect comments

---

src/object/omit.spec.ts
src/object/pick.spec.ts

I added code in the `object` related function test. (consistency, add test case)
In the `omit`function, one test case was changed by not using the `result` variable.
There was only one test case for the `pick` function.
I Added a test case.
- All keys are picked
- The key array is empty
- Nested objects

test(omit, pick): Add test cases

---

benchmarks/maxBy.bench.ts
docs/ko/reference/math/maxBy.md
docs/reference/math/maxBy.md
src/math/index.ts
src/math/maxBy.spec.ts
src/math/maxBy.ts

close #55 
I added a function that select element that have max value by given condition in array.
- If input array is not empty, return first element of array that have maximum value that satisfies given condition
- If input array is empty, return undefined

feat(maxBy): Add maxBy function that select element that have max value by given condition in array

---

benchmarks/minBy.bench.ts
docs/ko/reference/math/minBy.md
docs/reference/math/minBy.md
src/math/index.ts
src/math/minBy.spec.ts
src/math/minBy.ts

close #65 
I added a function that select element that have min value by given condition in array.
- If input array is not empty, return first element of array that have minimum value that satisfies given condition
- If input array is empty, return undefined

feat(minBy): Add minBy function that select element that have min value by given condition in array

---

docs/ko/reference/math/round.md
docs/reference/math/round.md
src/math/round.spec.ts
src/math/round.ts

When rounding, the type of the second parameter, `precision`, is Number, which can also accept float values. Therefore, I added exception handling for cases where it is not an Integer.
When attempting to use the round function with inputs like round(1.2345, 3.1), the result was 1.2343860767615331, which does not behave as desired for a rounding function. To fix this, I added exception handling with the following code.
```
if (!Number.isInteger(precision)) {
throw new Error('Precision must be an integer.');
}
```
This ensures that the `precision` parameter must be an integer, preventing incorrect rounding behavior.

fix(round): Throw an exception when `precision` is not an integer

---

src/math/random.ts

I have revised the explanation to correct inaccuracies. I have also included additional details to improve developers' understanding.

fix(random): correct JSDoc

---

src/array/difference.ts

I guess that when supporting read-only arrays, [the `readonly` keyword was mistakenly omitted](https://github.com/toss/es-toolkit/commit/e595e5e017e1f2cb138b1ad3d708635efc5e289e#diff-c6fd3af3ba9f40b9d78d4fbcdfaced66ca7ab40cdf9568ce602b006f045bb9ffL23-R23) from the `difference` parameter.

fix(difference): Add missing readonly to parameter

---

src/array/keyBy.spec.ts
src/array/keyBy.ts

https://github.com/toss/es-toolkit/pull/93#issuecomment-2198418191
Make number and symbol keys acceptable for the `keyBy` function.

feat(keyBy): Accept number and symbol keys in `keyBy`

---

src/array/groupBy.spec.ts
src/array/groupBy.ts

I think `groupBy`, like [`keyBy`](https://github.com/toss/es-toolkit/pull/98), should also accept number and symbol keys.

feat(groupBy): Accept number and symbol keys in groupBy

---

docs/ko/reference/array/groupBy.md
docs/ko/reference/array/keyBy.md
docs/reference/array/groupBy.md
docs/reference/array/keyBy.md

I missed to update docs after accepting number and symbol keys in  `groupBy` and `keyBy`

docs(groupBy, keyBy): Update type of key to PropertyKey

---

benchmarks/sampleSize.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/ko/reference/array/sampleSize.md
docs/reference/array/sampleSize.md
src/array/index.ts
src/array/sampleSize.spec.ts
src/array/sampleSize.ts

close #87 
I added the error checking code from the code discussed in the issue.
```ts
if (size > array.length) {
throw new Error('Size must be less than or equal to the length of array.');
}
```
If the user enter a size greater than the length of the array (e.g. `sampleSize([1, 2, 3], 4)`) in the absence of error checking code, the following error message is displayed.
> Error: Invalid input: The maximum value must be greater than the minimum value.
I think that error log is less relevant to `sampleSize`.
Feel free to tell me if you think it's unnecessary. 🙇‍♂️

feat(sampleSize): add sampleSize

---

benchmarks/meanBy.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/ko/reference/math/meanBy.md
docs/reference/math/meanBy.md
src/math/index.ts
src/math/mean.ts
src/math/meanBy.spec.ts
src/math/meanBy.ts

close #96 
I add the `meanBy` function based on the discussion in the issue.
I wrote the docs by `referring` to `mean`, `mixBy`, `maxBy`, and fixed a typo in `mean` annotation along the way.

feat(meanBy): add meanBy

---

benchmarks/once.bench.ts
docs/ko/reference/function/once.md
src/function/once.spec.ts

I found a mistake in the documentation and fixed it.
I think it's more explicit to check `toBeUndefined` if there is no return value.
I add `once.bench.ts`.

chore(once): fix docs and test, add bench

---

package.json

es-toolkit should have more detail in package.json
1. repository
2. issue
3. hompage
4. license
Compare https://www.npmjs.com/package/es-toolkit with https://www.npmjs.com/package/@suspensive/react
https://npmtrends.com/@suspensive/react-vs-@suspensive/react-query-vs-es-hangul-vs-es-toolkit-vs-overlay-kit

chore(package.json): add details

---

benchmarks/inRange.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/ko/reference/math/inRange.md
docs/reference/math/inRange.md
src/math/inRange.spec.ts
src/math/inRange.ts
src/math/index.ts

close #97
I add the `inRange` function based on the discussion in the issue.
Thanks.

feat(inRange): add inRange

---

benchmarks/invert.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/ko/reference/object/invert.md
docs/reference/object/invert.md
src/object/index.ts
src/object/invert.spec.ts
src/object/invert.ts

close: #116 
I added an invert function to the es-toolkit library. The invert function takes an object as input and returns a new object where the keys and values are swapped. This functionality is available in lodash but was not present in es-toolkit.
The invert function is particularly useful when you need to reverse the mapping of an object. For example, given an object with key-value pairs, the invert function will produce a new object where the original values become the keys and the original keys become the values.
For reference, you can see the lodash invert function [here.](https://lodash.com/docs/4.17.15#invert)

feat(invert): add invert

---

.github/workflows/release.yml

This PR adds `provenance` flags of npm to npm publishing step of `.github/workflows/release.yml`.
To learn more about the flag, please refer the following doc:
https://github.blog/2023-04-19-introducing-npm-package-provenance/

chore: add provenance flags to npm publishing step

---

.scripts/postbuild.sh
package.json

When I run the "yarn build" command, I get the following error. I think it's a matter of executive authority. Rather than setting the executive authority separately, I solved it by adding the "sh" command.

fix(package.json): build script

---

src/math/range.ts

I removed the incorrect explanation and added concrete information about the `range` function.

docs(range): Fix docs for range

---

src/object/invert.ts

Previously, the JSDoc of the `invert` function was invisible due to a space between the comment and the function. I couldn't read the JSDoc from my IDE, so I fixed this.

docs(invert): Ensure JSDoc visibility for `invert` function

---

.eslintrc.js

Previously, I [added a JSDoc ESLint rule](https://github.com/toss/es-toolkit/pull/112) to enforce consistent JSDoc comments. However, I found that 'jsdoc/require-jsdoc' is too strict because it requires JSDoc comments for **every** function. Therefore, I believe it would be better to disable this rule.

chore: Disable 'jsdoc/require-jsdoc' eslint rule

---

benchmarks/flatten.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/ko/reference/array/flatten.md
docs/reference/array/flatten.md
src/array/flatten.spec.ts
src/array/flatten.ts
src/array/index.ts

close: #137 
Implement the same function as `lodash's flattenDepth` under the name `flatten(arr, depth)`.
It works the same as [Array.prototype.flat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) provided by default in JavaScript and returns the same type. However, its performance is superior.

feat(flatten): add flatten

---

benchmarks/initial.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/.vitepress/zh_hans.mts
docs/ko/reference/array/initial.md
docs/reference/array/initial.md
docs/zh_hans/reference/array/initial.md
src/array/index.ts
src/array/initial.spec.ts
src/array/initial.ts

close #151 #95 
I have created a function that returns a new array containing all elements except the last one from the input array. 
Below is a performance comparison with Lodash. If you have any questions or comments, please feel free to share.
Thank you.

feat(initial): add `initial`

---

.gitignore

Ignores the folders that are created when using Visual Studio Code or IntelliJ or Webstorm IDE's

chore(gitignore): add vscode and intellij ide folders to gitignore

---

benchmarks/clone.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/ko/reference/object/clone.md
docs/reference/object/clone.md
src/object/clone.spec.ts
src/object/clone.ts
src/object/index.ts

Hello, @raon0211! 😁 I have implemented a clone function with shallow copy. However, I have some questions!
By plain objects, do you mean objects that are pure key-value pairs, excluding Date, Regex, Map, etc.? If so, I'm curious why you requested a clone that targets only plain objects and plain arrays in the issue.
Since this library is intended to target `lodash`, I wondered if it should support other types of data structures as well.
For now, I've added support for other data types, but I can change this based on your response :)
This is not directly related to clone, but I have a question since it overlaps with the topic of plain objects and plain arrays.
The relatively recent API, [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone), supports deep …

feat(clone): add clone

---

docs/reference/predicate/isEqual.md
src/predicate/index.ts
src/predicate/isEqual.spec.ts
src/predicate/isEqual.ts

This PR adds the `isEqual` function to the codebase. The `isEqual` function checks if two values are equal, including support for `Date`, `RegExp`, and deep object comparison. Additionally, this PR includes comprehensive tests and detailed documentation for the `isEqual` function.
- Added the `isEqual` function.
- Created test cases for `isEqual` using `vitest` to ensure the function works correctly for various scenarios.
- Added detailed documentation for the `isEqual` function in markdown format.
Please review the changes and provide feedback or approval for merging. Thank you!

feat(isEqual): add isEqual

---

benchmarks/sumBy.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/.vitepress/zh_hans.mts
docs/ko/reference/math/sumBy.md
docs/reference/math/sumBy.md
docs/zh_hans/reference/math/sumBy.md
src/math/index.ts
src/math/sumBy.spec.ts
src/math/sumBy.ts

- Added the `sumBy` function to sum array elements by mapping them to numeric values using a provided iteratee function.
- This function reuses the existing `sum` function.
- Added comprehensive documentation for `sumBy`in Korean, English and Chinese.
<table>
<tr>
<th> en </th>
<th> ko </th>
</tr>
<tr>
<td>
</td>
<td> <img width="784" alt="스크린샷 2024-07-15 오전 12 40 45" src="https://github.com/user-attachments/assets/28c725b2-2277-4f1d-a45b-7dd170d96571">
</td>
</tr>
<tr>
<th> zh </th>
</tr>
<tr>
<td> 
</td>
</tr>
</table>

feat(sumBy): add sumBy

---

docs/ko/reference/array/last.md

hello @raon0211. 
I remember that unnecessary error handling was deleted from the last function in the last pr #149. 
The English and Chinese are missing, but only the Korean docs are currently included, so I'll post a correction. 
thank you
- delete unnecessary error section in last-ko docs.

docs(last-ko): delete error category in last-ko docs

---

src/array/fill.ts

While reading the JSDoc for the `fill` function, I found that it included an incorrect explanation, so I fixed it.

docs(fill): fix docs for fill

---

src/compat/_internal/falsey.ts

The `falsey` constant was removed as it was not being used anywhere in the codebase. I think that removing unused code helps in maintaining a cleaner and more maintainable codebase. So, I removed it.

fix(falsey): remove unused `falsey` constant in `src/compat`

---

.github/CODE_OF_CONDUCT.md

When reading the [contributing guide](https://github.com/toss/es-toolkit/blob/main/.github/CONTRIBUTING.md), it directed me to the [code of conduct](https://github.com/toss/es-toolkit/blob/main/.github/CODE_OF_CONDUCT.md), which I found hard to read as rendered by GitHub because it seems to be lacking basic Markdown syntax despite using a `.md` extension.
In particular:
- headings were not marked as such;
- a list of bullet points was indented with 4 spaces (which is markdown syntax for a code block).
I referred to https://www.contributor-covenant.org/version/1/4/code-of-conduct/ to make sure the formatting I used matches the original document's structure.
I did not change any content. These changes are for readability only.

docs: fix formatting of CODE_OF_CONDUCT.md

---

src/object/invert.spec.ts
src/object/invert.ts

`lodash's invert` does not invert inherited properties.
This PR fixes the implementation of invert to be compatible with lodash's implementation
You may close this PR if you want inherited properties to be inverted :)

fix(invert): Fixed `invert` not to invert inherited properties

---

benchmarks/zipObjectDeep.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/ko/reference/array/zipObjectDeep.md
docs/reference/array/zipObjectDeep.md
src/array/index.ts
src/array/zipObjectDeep.spec.ts
src/array/zipObjectDeep.ts

#138
This pull request implements a function zipObjectDeep. This function takes two arrays: one containing arrays of property paths, and the other containing corresponding values.It returns a new object where paths from the first array are used as key paths to set values, with corresponding elements from the second array as values.Paths can be dot-separated strings or arrays of property names.If the `keys` array is longer than the `values` array, the remaining keys will have `undefined` as their values.
Below is a benchmark comparison between our head implementation and Lodash's head.

feat(zipObjectDeep): add zipObjectDeep

---

benchmarks/performance/get.bench.ts
docs/ko/reference/object/get.md
docs/reference/object/get.md
src/object/get.spec.ts
src/object/get.ts
src/object/index.ts

This PR addresses https://github.com/toss/es-toolkit/issues/215 and https://github.com/toss/es-toolkit/issues/91 by implementing the `get` function.

feat(get): add get

---

benchmarks/performance/endsWith.bench.ts
benchmarks/performance/startsWith.bench.ts
docs/ko/reference/string/endsWith.md
docs/ko/reference/string/startsWith.md
docs/reference/string/endsWith.md
docs/reference/string/startsWith.md
docs/zh_hans/reference/string/endsWith.md
docs/zh_hans/reference/string/startsWith.md
src/string/endsWith.spec.ts
src/string/endsWith.ts
src/string/index.ts
src/string/startsWith.spec.ts
src/string/startsWith.ts

similar to
* https://lodash.com/docs/4.17.15#startsWith
* https://lodash.com/docs/4.17.15#endsWith
```typescript
import { startsWith } from 'es-toolkit/string';
startsWith('fooBar', 'foo') // returns true
startsWith('fooBar', 'Bar') // returns false
startsWith('fooBar', 'abcdef') // returns false
startsWith('fooBar', 'Bar', 3) // returns true
```
```typescript
import { endsWith } from 'es-toolkit/string';
endsWith('fooBar', 'foo') // returns true
endsWith('fooBar', 'Bar') // returns false
endsWith('fooBar', 'abcdef') // returns false
endsWith('fooBar', 'foo', 3) // returns true
```

feat(startsWith): add startsWith and endsWith string functions

---

src/array/drop.spec.ts
src/array/drop.ts
src/array/dropRight.spec.ts
src/array/dropRight.ts

This PR fixes `drop` and `dropRight` to only allow positive integers.
This makes `drop` and `dropRight` compatible with lodash.

fix(drop): Fixed `drop` and `dropRight` only to allow positive integers

---

.circleci/config.yml

This pull request adds a prettier format check to our CI workflow, ensuring that only modified {js, ts, tsx} files are checked against the formatting rules. The comparison is made with the origin/main branch.
close #241 
> Additionally, there are currently many unformatted files, so we will also need a pull request to format these files using the yarn format command.

chore(ci): add Prettier format check to CI workflow

---

src/object/flattenObject.spec.ts

I have made a PR regarding the [take(compat) function](https://github.com/toss/es-toolkit/pull/252), but it failed due to issues in the flattenObject test case. 
The failure was caused by different date objects being used for comparison in the test cases. 
To fix this, I have modified the test cases to use a consistent date object for comparisons, ensuring that the date objects being compared are identical.
<table>
<tr>
<th>AS-IS </th>
</tr>
<tr>
<td>
</td>
</td>
</tr>
<tr>
<th>TO-BE</th>
</tr>
<tr>
<td> 
</td>
</tr>
</table>

test(flattenObject): change using constant date in test case

---

docs/compatibility.md
src/array/takeRight.ts
src/compat/array/last.spec.ts
src/compat/array/takeRight.spec.ts
src/compat/array/uniq.spec.ts
src/compat/initial.spec.ts
src/compat/without.spec.ts

Add the lodash compat tests for:
- [initial](https://lodash.com/docs/4.17.15#initial)
- [last](https://lodash.com/docs/4.17.15#last)
- [takeRight](https://lodash.com/docs/4.17.15#takeRight)
- [without](https://lodash.com/docs/4.17.15#without)
- [uniq](https://lodash.com/docs/4.17.15#uniq)
It also makes `takeRight` handle negative count correctly, let me know if it should be in a different PR or a different intended behavior is expected.

test(initial,last,takeRight,without,uniq): Add lodash compat tests

---

docs/.vitepress/ko.mts

I corrected the link to the mismatched document. (`ko/isTypedArray`)

docs(isTypedArray): fix isTypedArray ko docs link

---

src/compat/predicate/isNil.spec.ts
src/compat/predicate/isNil.ts

I implemented isNil in the compatibility version.
The test codes are referenced from [lodash isNil.spec.js](https://github.com/lodash/lodash/blob/main/test/isNil.spec.js).
I skipped `'should work with nils from another realm'` test case.

feat: add test case of isNil (compat version)

---

.circleci/config.yml

I think that integrating commands of eslint and prettier by using `xargs` is good for maintenance.
Add a shell property for unsetting `-o pipefail` option.
Circle CI sets this option by defaults. So If we don't have `.js` or `.ts` files, `grep` returns a `non-zero` exit code and as a result, this command also returns a `non-zero` exit code.
But we unset this option, even if `grep` returns a `non-zero` exit code, this command return a `zero` exit code.
We also have to check `.json` or etc files that has a javascript or json code.
> The file extension type is not matter, the language or content of file is matter.
So I remove `grep` command, because we have to check all of changed files includes `.json` and etc files.
But If we remove `grep` command, we can check unknown file like …

fix(ci): simplify and integrate lint code

---

docs/.vitepress/ko.mts

While looking at the official documentation in Korean, I saw that the link to 'function-negate' was specified as a link to the official documentation in English, so I created a pull request.

docs(negate): fix link of function-negate on ko docs

---

src/object/cloneDeep.ts

According to MDN
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer#description
the website must enable
```
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Embedder-Policy: require-corp
```
Otherwise, you'll get error: SharedArrayBuffer undefined

fix(cloneDeep): SharedArrayBuffer could be undefined

---

package.json
rollup.config.mjs

Fixes #284.
There were two issues reported in #284:
1. The source map for the `umd/browser.global.js` bundle was generated but not published in the package: fixed in #255.
2. The `umd/browser.global.js` path conveys the wrong information, because this bundle uses a simpler IIFE format declaring a global `_` variable, and not the UMD format.
This PR moves this bundle to `dist/browser.global.js`.
Because the Rollup config takes this path from `package.json#publishConfig#browser`, we only have to update it in `package.json`.

chore: move browser build from umd dir to dist

---

.scripts/postbuild.sh

Fixes #287.
This adds a couple lines of developer documentation in `.scripts/postbuild.sh` to convey this answer: https://github.com/toss/es-toolkit/issues/287#issuecomment-2248325627
Rationale: this might help other contributors to figure out the purpose of this setup, and could help down the line when deciding if these file are still needed (e.g. if future TypeScript versions change their defaults).
My personal taste veers towards documenting choices in code a lot, but if you'd rather avoid verbose developer comments that's perfectly fine. In that case, feel free to reject this PR and close #287 as needing no changes.

chore: add comment explaining purpose of root .d.ts files

---

src/predicate/isLength.ts

- By using `Number.isSafeInteger`, I simplify `typeof value === 'number' && value % 1 === 0 && value <= Number.MAX_SAFE_INTEGER` to `Number.isSafeInteger(value)`
- And I also change `value > -1` to `value >=0`, because I think that after code is more acceptable.
- There are no difference of performance.
``` typescript
export function isLength(value: unknown): value is number {
return Number.isSafeInteger(value) && (value as number) >= 0;
}
```
``` typescript
export function isLength(value: unknown): value is number {
return typeof value === 'number' && value > -1 && value % 1 === 0 && value <= Number.MAX_SAFE_INTEGER;
}
```

fix(isLength): modernize checking a safe integer

---

docs/ko/reference/predicate/isPrimitive.md
docs/reference/predicate/isPrimitive.md
docs/zh_hans/reference/predicate/isPrimitive.md
src/predicate/isPrimitive.ts

Object wrapper `object` makes it a little simpler to determine if it's a primitive.
This logic is possible because
1. undefined, null values return a new object. 
```ts
Object(); // {}
Object(undefined); // {}
Object(null); // {}
```
2. The primitive value is returned as an object wrapped in a wrapper object.
```ts
Object(true); // Boolean {true}
Object(1); // Number {1}
Object('str'); // String {''}
```
3. If the argument is an object, return it as is. 
```ts
const obj = { a: 1 }
const newObj = Object(obj); // { a: 1 }
obj === newObj; // true
const set = new Set();
const newSet = Object(set);
set === newSet; // true
```
So if the return value of `Object(value)` is different from `value`, it means it's an object.
Doesn't this make the implementation logic much simpler?

docs(isPrimitive): fix isPrimitive function documentations

---

benchmarks/performance/flatten.bench.ts
docs/compatibility.md
docs/ko/compatibility.md
docs/zh_hans/compatibility.md
src/compat/array/flatten.spec.ts
src/compat/array/flatten.ts
src/compat/index.ts

- **Array Type Checking:** Added a check to ensure the input value is an array. If the value is not an array, the function returns an empty array.
- **Flattening Items:** Enhanced the flattening mechanism for items that are either:
- Marked with `item[Symbol.isConcatSpreadable]` set to `true`
- Even though the `Array.prototype.flat` method does not support this, it was added for compatibility with lodash.
- Instances of `arguments`
- Instead of using the `isArguments` function, expressions are directly added for better performance.
- Items are forced to be of array type using `Array.prototype.from` for flattening the above types.

feat(flatten): add compatibility with lodash

---

benchmarks/performance/padStart.bench.ts
docs/.vitepress/en.mts
docs/reference/string/padStart.md
src/string/index.ts
src/string/padStart.spec.ts
src/string/padStart.ts

Instead of implementing a custom algorithm, I have utilized the built-in [String.prototype.padStart()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart) function in a more type safe way.
Resolves #280

feat(padStart): add padStart

---

docs/ko/reference/array/toFilled.md
docs/reference/array/toFilled.md
src/array/toFilled.ts

#326 
Hello,
I have modified the toFilled function to allow using arrays defined with as const. This enhancement will enable developers to use the function with immutable arrays, ensuring the original array remains unchanged.

feat: add readonly type for toFilled

---

docs/.vitepress/en.mts
docs/.vitepress/ko.mts

The `reference/array/size.html` documentation page has the wrong "shuffle" title in the menu.
See:
Fix it.

docs(size): fix size title

---

benchmarks/performance/flattenDeep.bench.ts
docs/compatibility.md
docs/ko/compatibility.md
docs/zh_hans/compatibility.md
src/compat/array/flattenDeep.spec.ts
src/compat/array/flattenDeep.ts
src/compat/array/flattenDepth.spec.ts
src/compat/array/flattenDepth.ts
src/compat/index.ts

I add `compat/flattenDeep` and `compat/flattenDepth` method based on `compat/flatten` function.
I don't add flattenDepth benchmark, because `flattenDepth` is same as `flatten` function.
close #262

feat(flattenDeep, flattenDepth): add compatibility with lodash

---

src/array/size.ts
src/object/cloneDeep.ts

We have two errors when running a release workflow. So I fixed them.
```bash
error: Is a directory (os error 21) Maybe specify path to 'index.ts' file in directory instead or run with --unstable-sloppy-imports
at file:///home/runner/work/es-toolkit/es-toolkit/src/array/size.ts:1:23
```
Before, it skip a filename in import path. So I just added it
``` bash
Check file:///Users/dayong/es-toolkit/src/object/cloneDeep.ts
error: TS2580 [ERROR]: Cannot find name 'Buffer'.
if (typeof Buffer !== 'undefined' && Buffer.isBuffer(obj)) {
~~~~~~
at file:///Users/dayong/es-toolkit/src/object/cloneDeep.ts:120:14
TS2580 [ERROR]: Cannot find name 'Buffer'.
if (typeof Buffer !== 'undefined' && Buffer.isBuffer(obj)) {
~~~~~~
at file:///Users/dayong/es-toolkit/src/object/cloneDeep.ts:120:40
TS2339 [ERROR]: …
```

fix(size, clonedeep): specify a file and ignore type error for deno

---

docs/reference/compat/string/endsWith.md

endsWith('fooBar', 'foo') // returns true -> false
endsWith('fooBar', 'Bar') // returns false -> true

docs(endsWith): Fix wrong returns in Examples

---

.github/workflows/release.yml
src/function/bind.ts

Normally, deno doesn't infer file extensions from imports.
But we add `--unstable-sloppy-imports` flag, then deno will infer file extensions.
> ref. https://docs.deno.com/runtime/manual/tools/unstable_flags/#--unstable-sloppy-imports
And I also add explicit symbol type in `bind` function for fixing deno error.

fix(bind, CD): add sloppy-import flag and explicit symbol type for publishing deno

---

benchmarks/performance/ary.bench.ts
benchmarks/performance/unary.bench.ts
benchmarks/performance/zipObjectDeep.bench.ts
src/compat/_internal/isSetMatch.spec.ts
src/compat/object/cloneDeep.spec.ts
src/compat/object/mapKeys.spec.ts
src/compat/object/mapKeys.ts
src/compat/object/property.spec.ts
src/compat/predicate/isMatch.spec.ts
src/compat/predicate/matches.spec.ts
src/object/mapKeys.ts
tests/utils/streamToBuffer.ts

- `benchmarks/performance/ary.bench.ts`: `no-unused-vars` error. This is a test code, so just add eslint-disable comment.
- `benchmarks/performance/unary.bench.ts`: `no-unused-vars` error. This is a test code, so just add eslint-disable comment.
- `benchmarks/performance/zipObjectDeep.bench.ts`: Remove unused variable.
- `src/compat/_internal/isSetMatch.spec.ts`: Remove unused import.
- `src/compat/object/cloneDeep.spec.ts`: Remove unused objects and style format.
- `src/compat/object/mapKeys.spec.ts`: `no-sparse-arrays` error. This is a test code, so just add eslint-disable comment.
- `src/compat/object/mapKeys.ts`: `[@typescript-eslint/ban-types](https://typescript-eslint.io/rules/ban-types)` error. I change to object type.
- `src/compat/object/property.spec.ts`: `no-unused-vars` error. …

chore: fix all lint errors

---

.circleci/config.yml

- I removed a unused slack orb.
- I add a branch linting all files in CI when .eslintrc.js, .prettierrc, .prettierignore files are changed.
- Because when we change the configure files, then maybe their rules are changed. So we need to lint all files that may have lint errors.
close #340

chore(ci): add a branch linting all files in CI when .eslintrc.js, .prettierrc, .prettierignore files are changed 

---

benchmarks/performance/indexOf.bench.ts
docs/compatibility.md
docs/ko/compatibility.md
docs/zh_hans/compatibility.md
src/compat/_internal/stubZero.ts
src/compat/array/indexOf.spec.ts
src/compat/array/indexOf.ts
src/compat/index.ts

I implement this function based on `Array.prototype.indexOf`.
Its behavior is  already similar with `lodash/indexof`.
> https://tc39.es/ecma262/#sec-array.prototype.indexof
But it can't find a `NaN` searchElement, so I add codes handling this case.
close #377

feat(indexOf): implement `indexOf` in `es-toolkit/compat`

---

benchmarks/performance/sortBy.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/ko/reference/array/sortBy.md
docs/reference/array/sortBy.md
src/array/index.ts
src/array/sortBy.spec.ts
src/array/sortBy.ts

I implement a `es-toolkit/sortBy` that sorts an array of objects based on the given iteratees or keys in ascending order.
This function have a custom key function feature differ from `es-toolkit/orderBy`.
> This function is based by `lodash/sortBy`, but more simple.
close #85

feat(sortBy): implement `es-toolkit/sortBy`

---

docs/reference/array/sortBy.md
docs/zh_hans/reference/array/sortBy.md
src/_internal/compareValues.ts
src/array/orderBy.ts
src/array/sortBy.ts

I think that `orderBy` function also has to use `_internal/compareValues` function.
So I add a `order` argument in `_internal/compareValues` function.

refactor(sortBy, orderBy): use same compareValues function in internal and fix type

---

benchmarks/performance/padEnd.bench.ts
benchmarks/performance/padStart.bench.ts
docs/reference/compat/string/padEnd.md
src/compat/index.ts
src/compat/string/padEnd.spec.ts
src/compat/string/padEnd.ts

We can use the native [padEnd](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padEnd) API instead of a custom solution.
Resolves #332

feat(compat): add `padEnd`

---

benchmarks/performance/orderBy.bench.ts
src/compat/_internal/getPath.ts
src/compat/array/orderBy.spec.ts
src/compat/array/orderBy.ts

`lodash/orderBy` has a feature of custom key functions, but `es-toolkit/compat/orderBy` doesn't have it.
I think that it makes confusion, so I added it.
related #383, #361

feat(orderBy): implement a feature of custom key functions in a `compat/orderBy`

---

src/compat/predicate/isObjectLike.ts

I've fixed the incorrect return type in the JSDoc and added the missing result in the example.

docs(isObjectLike): Update docs for `isObjectLike`

---

docs/zh_hans/reference/promise/timeout.md
src/promise/timeout.ts

I've corrected the docs for the `timeout` function.

docs(timeout): Update docs for `timeout`

---

src/promise/index.ts

Looks like the `timeout` function was mistakenly omitted from index.ts.

fix(timeout): Add missing export for `timeout`

---

benchmarks/performance/negate.bench.ts
docs/.vitepress/zh_hans.mts
eslint.config.mjs

Before, We ignored files in benchmarks, docs and tests. But we have to lint these files.
So I removed that part and add some patterns for built and node_modules.

chore(lint): fix ignores option

---

docs/ko/reference/array/countBy.md
docs/reference/array/countBy.md
docs/zh_hans/reference/array/countBy.md
src/array/countBy.ts

For consistency, the countBy function should support readonly arrays and non-string keys, like `groupBy`, so I made the change.

fix(countBy): Support nemeric and symbol keys in `countBy`

---

src/string/camelCase.ts

The JSDoc description for camel case describes snake case instead of camel case. This fixes it to be the correct definition.

docs(camelCase): Fix JSDoc for `camelCase`

---

docs/.vitepress/ko.mts

Hello, I noticed that the isSubset link in the Korean sidebar was pointing to the English documentation. I updated the link to correctly point to the Korean version /ko.

docs(isSubset): update isSubset path to /ko in the Korean documentation

---

docs/ja/reference/function/throttle.md
docs/ko/reference/function/throttle.md
docs/reference/function/throttle.md
docs/zh_hans/reference/function/throttle.md
src/function/throttle.ts

I changed types like this PR(https://github.com/toss/es-toolkit/pull/406).
I think that `throttle` also have to change its types for same reason.

fix(throttle): fix types of generic and return value

---

src/array/tail.ts

this change not only improve code readability but also improve performance in large array.
i ran this bench to check `tail` in large array
```ts
import { bench, describe } from 'vitest';
import { tail as tailToolkit } from 'es-toolkit';
import { tail as tailLodash } from 'lodash';
// Helper function to generate a large array
function generateLargeArray(size) {
return Array.from({ length: size }, (_, index) => index);
}
describe('tail', () => {
const largeArray = generateLargeArray(1000000);
bench('es-toolkit/tail', () => {
tailToolkit(largeArray);
});
bench('lodash/tail', () => {
tailLodash(largeArray);
});
});
```
updated code is more faster than original code.

refactor(tail): Improve code readability in `tail`

---

src/function/negate.spec.ts
src/function/negate.ts

Before the change, I encountered a type error when using the negate function with a function that has parameters.
I have updated the parameter type of negate so that it now supports functions with parameters.

fix(negate): Fix parameter type of `negate`

---

benchmarks/performance/pad.bench.ts
docs/.vitepress/en.mts
docs/reference/string/pad.md
src/string/index.ts
src/string/pad.spec.ts
src/string/pad.ts

This pull request introduces a [pad](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) function that pads a string on both the left and right sides if it is shorter than the specified length. The padding characters are truncated if they cannot be evenly divided by the length.
Resolves #386

feat(pad): add `pad` function

---

src/array/countBy.ts

Added missing example in jsdoc of `countBy` function.

fix(countBy): add missing example in jsdoc

---

README-ja_jp.md
README-ko_kr.md
README-zh_hans.md
README.md

This PR adds a badge with a invite link to the official Toss OSS Discord server.

docs: Add link to official Discord

---

src/function/negate.ts

Added missing example in jsdoc of `negate` function.

fix(negate): add missing example

---

benchmarks/performance/camelCase.bench.ts
src/compat/_internal/caseCompatLayer.ts
src/compat/_internal/normalizeForCase.ts
src/compat/index.ts
src/compat/string/camelCase.spec.ts
src/compat/string/camelCase.ts

I added `camelCase` in compat layer.
And I add a `normalizeForCase` internal function, because the other case functions also need to remove constraction apostrophes and handle case that the `str` argument is a `object`.
related #508

feat(camelCase): implement `camelCase` in compat layer

---

.scripts/tests/_internal/formatter/brokenSyntax.ts
.scripts/tests/_internal/transform/import.ts
.scripts/tests/_internal/transform/lodashStable.ts
.scripts/tests/transform-lodash-test.ts
package.json
yarn.lock

I added codemod for transform lodash test code based on `jscodeshift`.
It also format transformed source codes by `prettier`.
1. Choose the test code in [here](https://github.com/lodash/lodash/tree/main/test) and copy it.
2. Create a test file such as `src/compat/array/at.spec.ts`, then paste the code into the file.
3. Run the following command in the terminal to execute the transform:
``` bash
yarn transform "./src/compat/array/at.spec.ts"
```
- Import Statements:
- Automatically adds `import { describe, it, expect } from 'vitest';` at the top of the file.
- Removes import statements from the lodash library like `import lodashStable from lodash`.
- Changes tools imported from `./utils` to `../internal/` and splits them accordingly. (e.g. `import {stubTrue, stubFalse} from './utils';` => …

chore(test): add script for transforming lodash test codes

---

src/string/deburr.ts

before
after
**However, if the input string does not have any characters that need to be deburr'd, the performance of the lodash implementation improves dramatically in long words case. Is this acceptable?**

perf(deburr): improve performance

---

benchmarks/performance/isObject.bench.ts
docs/ko/reference/compat/predicate/isObject.md
docs/reference/compat/predicate/isObject.md
src/compat/index.ts
src/compat/predicate/isObject.spec.ts
src/compat/predicate/isObject.ts

benchmark
There is an isObjectLike function, but not an isObject, so I implemented it.
I would appreciate any feedback and reviews.

feat(compat): Add `isObject` function 

---

src/object/clone.spec.ts
src/object/clone.ts

Changes:
- It supports `DataView`, `Error`, `TypedArray`, `File`, `ArrayBuffer`, `Blob`, `Buffer`, `SharedArrayBuffer`.
- I simplified the codes
- Using `prototype.constructor()` instead of specified constructors  like `new Date()`(Also it's good for the exteneded Error instance.)
- Using `obj` instead of property value like `obj.gettime()`, `obj.source`
- Removing `isPrimitive()` that is a duplicated function.
- I fixed that we forget to copy `lastIndex` property in a `RegExp` object.

feat(clone): enhance clone function to handle various data types 

---

docs/ja/reference/compat/predicate/isObject.md
docs/ko/reference/compat/predicate/isObject.md
docs/reference/compat/predicate/isObject.md
docs/zh_hans/reference/compat/predicate/isObject.md
src/compat/predicate/isObject.ts

All example code that should have been written as `isObject` has been modified to be written as `isArray`.

fix : wrong docs in isObject docs

---

docs/ja/usage.md
docs/ko/usage.md
docs/usage.md
docs/zh_hans/usage.md

The pnpm official documentation recommends using the `add` command instead of `install` when installing new packages as follows:
- https://pnpm.io/cli/add
- https://pnpm.io/cli/install
Currently it works the same without any differences, but the document clearly distinguishes these two commands.
This means that you have the flexibility to adapt to changes, such as changing or removing commands in future versions.

docs: replace `pnpm install` with `pnpm add`

---

benchmarks/performance/isDate.bench.ts
docs/ja/reference/predicate/isDate.md
docs/ko/reference/predicate/isDate.md
docs/reference/predicate/isDate.md
docs/zh_hans/reference/predicate/isDate.md
src/predicate/index.ts
src/predicate/isDate.spec.ts
src/predicate/isDate.ts

Hi there. I'm inspired by your work. Thanks for the awesome contribution! 👍 
implements [isDate](https://lodash.com/docs/4.17.15#isDate) at predicate

feat(isDate): add `isDate` function

---

src/compat/array/drop.spec.ts
src/compat/array/drop.ts
src/compat/index.ts

|`drop.spec.ts`|
|---------------|
|<img src="https://github.com/user-attachments/assets/b3fefae7-81bd-4d90-84e1-17d8d3020258" width=720 height=240/>|
As mentioned in  Issue #531, which I opened, I wrote code to add compatibility to `drop.ts`. I also wrote additional test code and uploaded screenshots showing that it works properly.

feat(drop): Added compatibility for `drop`

---

src/array/zip.ts

I've improved the performance of `zip` by defining the array size. The updated code is 1.41x faster than the previous version.

perf(zip): Optimize performance of `zip`

---

src/array/zipWith.ts

I've optimized performance of `zipWith`

perf(zipWith): Optimize performance of `zipWith`

---

.scripts/tests/_internal/formatter/brokenSyntax.ts
.scripts/tests/_internal/transform/assert.ts
.scripts/tests/_internal/transform/import.ts
.scripts/tests/_internal/transform/lodashStable.ts
.scripts/tests/transform-lodash-test.ts

I improved transforming lodash test codes script:
1. Change `delete localVariable` to comment, Because this expression is not allowed in js strict mode.
2. Enhance fixing a broken syntax like `expect(a, [1, 2).toEqual(3])`.
a. Now, we can handle cases like `expect(func()`, `expect({a: {b: [1,2]}`, etc...
3. Change `assert.methods(a,b,c)` to `expect(a,c).toMethods(b)`.
b. e.g. `assert.strictEqual(a,b,c)` to `expect(a, c).toBe(b)`
4. Change `lodashStable.methods` to `esToolit.methods`
5. Change `import method from '../src/method'` to `import { method } from '../index'`
At now, We can transform all of the lodash testcode except 2 files.
I have automated the transformation of all lodash test codes as much as possible, but there are cases where the test code itself is inaccurate. Therefore, we …

chore(script): enhance transforming lodash test codes script

---

benchmarks/performance/upperCase.bench.ts
src/compat/index.ts
src/compat/string/camelCase.ts
src/compat/string/kebabCase.ts
src/compat/string/lowerCase.ts
src/compat/string/snakeCase.ts
src/compat/string/startCase.spec.ts
src/compat/string/startCase.ts
src/compat/string/upperCase.spec.ts
src/compat/string/upperCase.ts

I added a `upperCase` in compat layer.
And I fixed function interface similar with `@types/lodash`.

feat(string): implement `compat/upperCase` and fix types and jsdoc of case methods

---

docs/ko/bundle-size.md
docs/ko/compatibility.md
docs/ko/intro.md
docs/ko/usage.md

- fix typos and incorrect spacing
- fix untranslated comments in codeblock

docs: fix typo in `/bundle-size`, `/compatibility`, `/intro`, `/usage`

---

benchmarks/performance/isBoolean.bench.ts
benchmarks/performance/isRegExp.bench.ts
benchmarks/performance/isString.bench.ts
benchmarks/performance/isSymbol.bench.ts
src/compat/predicate/isBoolean.ts
src/compat/predicate/isNumber.ts
src/compat/predicate/isRegExp.ts
src/compat/predicate/isString.ts
src/compat/predicate/isSymbol.ts

If Class like `String` exists, I think that we don't need to compare with string like`[Object string]`, when checking wrapped value like `Object('str')`.
Additionally, I changed the parameter name of `isBoolean` to value for consistency, and added optional types to both `isBoolean` and `isString` for compatibility with Lodash.
---
---
---
---

fix(predicate): enhance performance and simplify codes of `isNumber`, `isString`, `isSymbol`, `isRegExp`, `isBoolean`

---

src/math/range.ts

I've updated the JSDoc for `range` to describe only the corresponding overloaded function signatures.

docs(range): Update docs for `range`

---

docs/ja/reference/string/startCase.md
docs/ko/reference/string/startCase.md
docs/reference/string/startCase.md
docs/zh_hans/reference/string/startCase.md
src/string/startCase.spec.ts
src/string/startCase.ts

Hi there 👍 
I saw some [strange behavior at startCase](https://github.com/toss/es-toolkit/issues/580)
so I handle this issue at original path's startCase (non-compat)
> I did not handle compat's startCase, but if you think it's necessary, I'll apply it! 
> Please feel free to talk about it 😄 
fix #580 
- #517 
- #313
- #203

fix(startCase): convert the non-first char to lowercase

---

benchmarks/performance/isSet.bench.ts
docs/ko/reference/predicate/isSet.md
docs/reference/predicate/isSet.md
src/predicate/index.ts
src/predicate/isSet.spec.ts
src/predicate/isSet.ts

Hi!🖐️
I appreciate your great works for environment!
I added `isSet` function.

feat(isSet): add isSet

---

src/compat/string/camelCase.spec.ts
src/compat/string/kebabCase.spec.ts
src/compat/string/lowerCase.spec.ts
src/compat/string/snakeCase.spec.ts
src/compat/string/startCase.spec.ts
src/compat/string/startCase.ts
src/compat/string/upperCase.spec.ts

Due to [the change](https://github.com/toss/es-toolkit/pull/591) in the behavior of `startCase` in `es-toolkit`, the tests for `startCase` in `es-toolkit/compat` should have failed, but they did not. Upon investigation, I found that some test cases were either incorrect or missing.
I have added the missing test cases and separated the code according to the differences in behavior.

fix(startCase): add missing tests and separate logic for `es-toolkit` and `es-toolkit/compat`

---

src/object/clone.ts

It is related this [comment](https://github.com/toss/es-toolkit/pull/312#issuecomment-2357611703)

fix(clone): `SharedArrayBuffer` could be `undefined`

---

benchmarks/performance/flow.bench.ts
docs/reference/function/flow.md
docs/zh_hans/reference/function/flow.md
src/function/flow.spec.ts
src/function/flow.ts
src/function/index.ts

feat(flow): implement flow

---

src/function/throttle.spec.ts
src/function/throttle.ts

- `throttle` fails to throttle its callback function after initial `throttleMs` delay. 
- Fixed the issue by updating the `pendingAt` timestamp when the callback function is executed. 
```ts
import { throttle } from "es-toolkit";
const startedAt = Date.now();
const throttledFunc = throttle(() => console.log(Date.now() - startedAt), 1_000);
setInterval(throttledFunc, 100);
// AS-IS: 100, 1102, 1202, 1301, ...
// TO-BE: 100, 1102, 2104, 3108, ...
```

fix(throttle): not throttling after initial throttleMs

---

yarn.lock

This is just the output of running `yarn dedupe`. Improves CI time, project's install time and disk space usage. My suggestion would be to make it a habit to dedupe after updating dependencies of any kind to avoid this problem in the future.

chore: dedupe dependencies

---

benchmarks/performance/every.bench.ts
docs/ko/reference/array/every.md
docs/reference/array/every.md
src/array/every.spec.ts
src/array/every.ts
src/array/index.ts

#293 
This pull request implements the `every` function, which behaves similarly to the [every function in lodash](https://lodash.com/docs/4.17.15#every).
The function takes a collection and a predicate function as parameters and checks if all elements in the collection pass the predicate, returning true or false..
Below is a benchmark comparing our `every` function to lodash's `every`.

feat(every): Add `every` function

---

src/object/merge.spec.ts
src/object/merge.ts

I understood how the `merge` function works by testing Lodash's `merge` function. I then realized there was a difference between the two.
Although this is not `compat/merge`, the behavior should be consistent. Please let me know if the current behavior is intended.

fix(merge): Handle edge-case for `merge`

---

docs/ja/reference/predicate/isEqual.md
docs/ko/reference/predicate/isEqual.md
docs/reference/predicate/isEqual.md
docs/zh_hans/reference/predicate/isEqual.md

Since in es-toolkit and lodash, `isEqual` returns `true` when comparing`+0` and `-0`, i updated document.

docs(isEqual): Correct result of special case

---

src/compat/object/pick.ts

changing `ProperyKey[][]` to `PropertyKey[][]` and fixing a missing space in `keysgoes`to `keys goes`.

docs(pick): PropertyKey typo and fix spacing

---

src/math/range.ts

`range` was returning `any[]`. Updated it to explicitly return `number[]` by using `new Array<number>(length)` for better type safety. `range` should always return an array of numbers.

refactor(range): Enhance type safety in the implementation

---

benchmarks/performance/isArrayBuffer.bench.ts
src/compat/index.ts
src/compat/predicate/isArrayBuffer.spec.ts
src/compat/predicate/isArrayBuffer.ts
src/predicate/isArrayBuffer.ts

I added `isArrayBuffer` in compat.

feat(compat) : implement `isArrayBuffer` compat

---

benchmarks/performance/before.bench.ts
src/compat/function/before.spec.ts
src/compat/function/before.ts
src/compat/index.ts

Our implementation of `before` returns `undefined` after the `n-1` call, while Lodash's implementation returns the result of the `n-1` call. Therefore, I couldn't use our function, so I re-implemented.
The issue arises due to the overhead involved when importing the module, which is causing this result. If we resolve the part where `toInteger` is imported, the output will be the same as Lodash.

feat(before): add `before` in compat layer

---

docs/ja/reference/function/before.md
docs/ja/reference/function/once.md
docs/ko/reference/function/before.md
docs/ko/reference/function/once.md
docs/reference/function/before.md
docs/reference/function/once.md
docs/zh_hans/reference/function/before.md
docs/zh_hans/reference/function/once.md
src/function/before.ts
src/function/once.ts

- `before`
- I corrected the part where the return type was defined as the assigned function, even though it returns a new function.
- `once`:
- Previously, the function was designed to only accept functions without arguments, but we needs to accept functions with arguments. So I added this feature.
- I simplified the code a bit.

fix(before,once): allow accepting arguments for `once` and fix types of `before` and `once`

---

src/compat/array/includes.ts
src/compat/predicate/isMatch.ts
src/predicate/isEqualWith.ts

This refactor updates the code by replacing direct expressions with calls to the `eq` function. It makes the code slightly slower but enhances consistency and readability across the codebase.
I also was going to modify `defaults`, but you’ve already taken care of it, so thank you! Also, thank you for removing `eq` inside `_internal`!

refactor: replace direct expressions with `eq` function calls

---

.gitignore
benchmarks/performance/isRegExp.bench.ts
benchmarks/performance/isString.bench.ts
benchmarks/performance/isSymbol.bench.ts
vitest.config.mts

ref:  https://discord.com/channels/1281071127052943361/1281085859608924282/1291310699351638087
now we have two bundles when benchmarking

bench: pre-build es-toolkit when bench

---

benchmarks/performance/times.bench.ts
src/compat/_internal/doubled.ts
src/compat/_internal/stubArray.ts
src/compat/index.ts
src/compat/util/times.spec.ts
src/compat/util/times.ts

I added `times` in compat layer. 
I prioritized its implementation because it frequently appeared in compatibility tests.

feat(times): add `times` in compat layer

---

src/object/omitBy.ts
src/object/pickBy.ts

https://github.com/toss/es-toolkit/pull/671
This is the same as the PR above.
Change from `Object.Entries` to `Object.keys`.

perf(pickBy): improve pickBy performance

---

docs/ja/reference/function/throttle.md
docs/ko/reference/function/throttle.md
docs/reference/function/throttle.md
docs/zh_hans/reference/function/throttle.md

#668 
I have added documentation for the { leading: false, trailing: true } option in throttle, as it could cause confusion based on how Lodash handles it.

docs(throttle): Update docs

---

src/predicate/isPlainObject.spec.ts
src/predicate/isPlainObject.ts

Hello, I'm really impressed by estoolkit. Great !
I'm porting few more tests and fixes to the isPlainObject implementation. Mostly taken from my own isPlainObject implementation: see https://github.com/belgattitude/httpx/tree/main/packages/plain-object#readme
This fix few bugs that I found. So I've completed the test suite. 
- #694 
- #693 
- #695 
Should also bring a >3x speedup based on my "real-world" scenarios
https://github.com/belgattitude/httpx/tree/main/packages/plain-object#benchmarks
After the changes
```
✓ benchmarks/performance/isPlainObject.bench.ts > isPlainObject 3920ms
name                                       hz     min     max    mean     p75     p99    p995    p999     rme  samples
· es-toolkit/isPlainObject         2,519,342.19  0.0004  0.0325  0.0004  0.0004  0.0007 …
```

fix(isPlainObject): Fix isPlainObject and perf 3x+

---

benchmarks/performance/dropRight.bench.ts
docs/ja/reference/array/dropRightWhile.md
docs/ja/reference/array/dropWhile.md
docs/ko/reference/array/dropRightWhile.md
docs/ko/reference/array/dropWhile.md
docs/reference/array/dropRightWhile.md
docs/reference/array/dropWhile.md
docs/zh_hans/reference/array/dropRightWhile.md
docs/zh_hans/reference/array/dropWhile.md
src/compat/array/drop.spec.ts
src/compat/array/drop.ts
src/compat/array/dropRight.spec.ts
src/compat/array/dropRight.ts
src/compat/array/dropRightWhile.spec.ts
src/compat/array/dropRightWhile.ts
src/compat/array/dropWhile.spec.ts
src/compat/array/dropWhile.ts
src/compat/index.ts

After this PR, dropWhile and dropRightWhile are still a bit different from lodash:
lodash: 
```ts
function dropWhile<T>(
arr: ArrayLike<T> | null | undefined,
canContinueDropping: (item: T, index: number, arr: ArrayLike<T>) => unknown
): T[];
```
es-toolkit: 
```ts
function dropWhile<T>(
arr: ArrayLike<T> | null | undefined,
canContinueDropping: (item: T, index: number, arr: T[]) => unknown
): T[];
```
The third argument to `canContinueDropping` in lodash is the same as `arr`, but the third argument to `canContinueDropping` in es-toolkit is `Array.from(arr)`.
If we want to modify it, we can't use `dropWhileToolkit`/`dropRightWhileToolkit` in the compat layer, because it doesn't support ArrayLike.

fix(drop): support array-like args

---

src/compat/array/orderBy.spec.ts
src/compat/array/orderBy.ts
src/compat/array/sortBy.spec.ts
src/compat/array/sortBy.ts

- `orderBy` should support `ArrayLike`
- `orderBy criteria` should treat `[]` as `undefined`
- `sortBy` should support `ArrayLike`
- `sortBy` should support rest criteria

fix(orderBy/sortBy): fix lodash compatibility

---

benchmarks/performance/intersectionBy.bench.ts
docs/ja/reference/array/intersectionBy.md
docs/ko/reference/array/intersectionBy.md
docs/reference/array/intersectionBy.md
docs/zh_hans/reference/array/intersectionBy.md
src/compat/array/intersectionBy.spec.ts
src/compat/array/intersectionBy.ts
src/compat/index.ts

I added the `intersectionBy` function to the compatibility layer.

feat(intersectionBy): Add `intersectionBy` to compatibility layer

---

docs/ja/reference/array/intersection.md

This PR fixes the typo on the Intersection page of the Japanese documentation as noted in the issue(#734).
Corrected "公通" to "共通" in the text.

docs(intersection): fix typo

---

docs/ja/reference/compat/math/floor.md
docs/ja/reference/compat/math/parseInt.md
docs/ja/reference/compat/predicate/isNaN.md
docs/ja/reference/compat/util/toInteger.md
docs/ja/reference/predicate/isMap.md
docs/ja/reference/predicate/isRegExp.md
docs/ja/reference/predicate/isSet.md

docs(isMap, isNaN, isRegExp, isSet, toInteger, parseInt, floor): correct translation errors

---

src/object/merge.ts

Is there a reason not to define the types of arguments to the `merge` function more narrowly? 
Given the purpose of the `merge` function and most use cases, I think it's appropriate to narrow the type of the source and destination to `Object`.
What do you think? 
Currently, the following cases are allowed 
Do we really need to allow this? 🤔
```ts
// as-is
merge(1, 2); // type pass
```

fix(merge): improved merge function types

---

benchmarks/performance/uniqueId.bench.ts
docs/ja/reference/compat/util/uniqueId.md
docs/ko/reference/compat/util/uniqueId.md
docs/reference/compat/util/uniqueId.md
docs/zh_hans/reference/compat/util/uniqueId.md
src/compat/index.ts
src/compat/util/uniqueId.spec.ts
src/compat/util/uniqueId.ts

Implemented lodash's uniqueId. 
If there is anything that needs supplementation, please give me feedback. 
I will fix it right away. 
Thank you.

feat(uniqueId): Add uniqueId to compat layer

---

benchmarks/performance/replace.bench.ts
src/compat/index.ts
src/compat/string/replace.spec.ts
src/compat/string/replace.ts

I added `replace` to compat layer.
It utilizes `String.prototype.replace`, resulting in minimal performance difference compared to Lodash. Additionally, I decided not to include it in the original es-toolkit as it seemed unnecessary.
Furthermore, using a union type in the replacement part causes an error. To circumvent this, I temporarily asserted it as `any`.
> related [Issue](https://github.com/microsoft/TypeScript/issues/22378)

feat(replace): add `replace` to compat layer

---

src/math/sum.ts
src/math/sumBy.ts

This changes `sumBy` to avoid allocating an array (from `.map`) - instead the sum is computed with a simple accumulating number. This should be a strict improvement. I also took the opportunity to implement `sum` in terms of `sumBy` to save code size if both are imported, since they're basically the same function.
I don't trust these benchmarks at all - this claimed no benefit to my change, and it also claims lodash is 50% faster on the large array case *even if I replace `sumBy`'s implementation with lodash's implementation!* Perhaps vite is adding some overhead.

fix(sumBy, sum): Remove array allocation from sumBy

---

benchmarks/performance/iteratee.bench.ts
src/compat/index.ts
src/compat/util/iteratee.spec.ts
src/compat/util/iteratee.ts

I added `iteratee` to compat layer.
```typescript
it('should use internal `iteratee` if external is unavailable', () => {
const iteratee = _.iteratee;
delete _.iteratee;
expect(map([{ a: 1 }], 'a')).toEqual([1]);
_.iteratee = iteratee;
});
```
The above test case has been commented out because it needs to be implemented in the `map`.
block #759
close #760

feat(iteratee): add `iteratee` to compat layer

---

src/compat/string/replace.spec.ts
src/compat/string/replace.ts

I added an [edge case for the argument length of less than 3](https://github.com/lodash/lodash/blob/ddfd9b11a0126db2302cb70ec9973b66baec0975/lodash.js#L14540) to ensure compatibility with Lodash.

fix(replace): Handle cases with less than 3 arguments

---

src/array/without.ts

This can be implemented simply by reusing the `difference` function for the `without` function!! 🤗
```ts
// as-is
export function without<T>(array: readonly T[], ...values: T[]): T[] {
const valuesSet = new Set(values);
return array.filter(item => !valuesSet.has(item));
}
export function difference<T>(firstArr: readonly T[], secondArr: readonly T[]): T[] {
const secondSet = new Set(secondArr);
return firstArr.filter(item => !secondSet.has(item));
}
```
```ts
// to-be
export function without<T>(array: readonly T[], ...values: T[]): T[] {
return difference(array, values);
}
```
Despite the differences in the interface of the two functions, the internal logic is the same, so they can be reused 👍

refactor(without): improved by reusing the difference function in the without function

---

src/array/isSubsetWith.ts

Related Pull Request: https://github.com/toss/es-toolkit/pull/783
The `isSubset` function is simply implemented by reusing the `difference` function.
```ts
export function isSubset<T>(superset: readonly T[], subset: readonly T[]): boolean {
return difference(subset, superset).length === 0;
}
```
I think the same is true for the `isSubsetWith` function. It can be implemented simply by reusing `differenceWith`.
cc. @kaehehehe

refactor(isSubsetWith): improved by reusing the differenceWith in the isSubsetWith

---

benchmarks/performance/findKey.bench.ts
docs/ja/reference/object/findKey.md
docs/ko/reference/object/findKey.md
docs/reference/object/findKey.md
docs/zh_hans/reference/object/findKey.md
src/object/findKey.spec.ts
src/object/findKey.ts
src/object/index.ts

Related issues: https://github.com/toss/es-toolkit/issues/715
Before implementing findKey in the compat layer, I preemptively worked on es-toolkit's findKey.
Hi!, @raon0211 
There is something that needs your opinion.
There was a point where I was focused while implementing it, and that was how strictly to keep the type. 
In the case of lodash's findKey, if an object is received as the first argument of findKey, the return value is a simple string. 
However, in the case of findKey that I implemented, the key value of the object is specified as the return value. 
Since this is not a compat layer, I think it is right to follow the principles of es-toolkit rather than lodash, so I need your opinion on that.
I believe that in order for TypeScript to be used meaningfully, it is right to …

feat(findKey): add findKey

---

src/compat/util/toPath.ts

The currently used regular expressions in `toPath()` are expensive, so this PR changes the implementation to not rely on them. Because `toPath` is used in `get`, `set`, `unset`, `has`, and `orderBy`, performance of these functions is also improved.
Performance improvements:
* `toPath()`
* `toPath: super simple` — 840%
* `toPath: dots` — 830%
* `toPath: brackets` — 1270%
* `toPath: complex` — 1340%
* `get()`
* `get with string` — 420%
* `get with string array` — 15%
* `has()`
* `has with string` — 450%
* `orderBy()`
* `orderBy (property path)` — 36%
* `set()`
* `set - dot` — 91%
* `set - array` — 119%
* `unset()`
* `unset` — 155%
After these changes, performance of these functions is in most cases on par with lodash.
---
Before:
---
After:
---

perf: Improve performance of `toPath`, `get`, `set`, `unset`, `has`, `orderBy`.

---

src/compat/_internal/ensureIsArray.ts
src/compat/_internal/toArray.ts
src/compat/array/chunk.ts
src/compat/array/difference.ts
src/compat/array/drop.ts
src/compat/array/dropRight.ts
src/compat/array/dropWhile.ts
src/compat/array/findLastIndex.ts
src/compat/array/head.ts
src/compat/array/last.ts
src/compat/array/sample.ts
src/compat/array/tail.ts
src/compat/array/take.ts
src/compat/array/takeRight.ts

Various compatibility array functions are slow when handling large arrays, which is largely caused by unnecessary `Array.from()` calls. This PR adds a check, so `Array.from()` is only called when necessary.
Below are performance improvements for the `head` function. Results for other methods are similar.
Before:
---
After:

perf(compat/array): Improve performance of various array functions in `compat`

---

benchmarks/performance/uniqBy.bench.ts
src/compat/array/uniqBy.spec.ts
src/compat/array/uniqBy.ts
src/compat/index.ts

I added uniqBy in compat layer
issue https://github.com/toss/es-toolkit/issues/784
benchmark

feat(uniqBy): add uniqBy to compat layer

---

src/compat/_internal/flattenArrayLike.spec.ts
src/compat/_internal/flattenArrayLike.ts
src/compat/array/differenceBy.spec.ts
src/compat/array/differenceBy.ts

Since the `differenceBy(compat)` function needs to pass the test cases in the [difference-methods spec](https://github.com/lodash/lodash/blob/6a2cc1dfcf7634fea70d1bc5bd22db453df67b42/test/difference-methods.spec.js#L1), I added it to our spec.
After adding this test, I found that two tests were failing, so I fixed them:
- It should work with array-like objects.
- It should filter out values that are not arrays or array-like objects.

fix(differenceBy): Update `differenceBy` function to handle array-like objects and filter out invalid values

---

src/object/flattenObject.spec.ts
src/object/flattenObject.ts

fix(flattenObject): flatten for nested objects

---

src/compat/util/toArray.ts

In fact, isArrayLike already overrides the string case

fix(toArray): simplify impl

---

benchmarks/performance/findKey.bench.ts
docs/ja/reference/object/findKey.md
docs/ko/reference/object/findKey.md
docs/reference/object/findKey.md
docs/zh_hans/reference/object/findKey.md
src/compat/index.ts
src/compat/object/findKey.spec.ts
src/compat/object/findKey.ts

Implemented lodash's findKey. 
If there is anything that needs to be supplemented, please give me feedback. 
I will supplement it. 
Thank you 🙏🙏

feat(findKey): add findKey to compat layer

---

benchmarks/performance/nth.bench.ts
docs/ja/reference/compat/array/nth.md
docs/ko/reference/compat/array/nth.md
docs/reference/compat/array/nth.md
docs/zh_hans/reference/compat/array/nth.md
src/compat/_internal/stubA.ts
src/compat/_internal/stubB.ts
src/compat/array/nth.spec.ts
src/compat/array/nth.ts
src/compat/index.ts

I added `nth` to the compatibility layer. While fixing the failed test cases, I discovered that `stubA` and `stubB` were incorrect, so I also fixed them.

feat(nth): add `nth` to compat

---

docs/ja/reference/compat/array/castArray.md
docs/ja/reference/compat/object/get.md
docs/ja/reference/compat/object/property.md
docs/ko/reference/compat/array/castArray.md
docs/ko/reference/compat/object/get.md
docs/ko/reference/compat/object/property.md

Although there is 'readonly' in the actual interface, it appears to be the overall writing guideline of es-toolkit to omit 'readonly' from arguments and return types when describing method interfaces in the docs. However, I found and fixed inconsistencies in several functions where this wasn't followed.

docs: Remove unnecessary readonly keywords

---

src/array/groupBy.spec.ts
src/array/groupBy.ts

- Fix the `groupBy` function to properly preserve Object prototype (like `toString`, `valueOf`).
While implementing "[fix(groupBy): Support keys like toString or valueOf in groupBy](https://github.com/toss/es-toolkit/commit/1f336b045692e06f852c9b87064a3ae8c5577c7c#diff-636dea33563199f80586e9579e588a6bd655799bd2e43fbed0d3a13ed9286468R27)", we noticed that prototype methods were removed entirely. This is likely unintended behavior unless the user specifically uses these method names as keys.
For example, even when not using 'toString' as a grouping key, attempting to convert the result object to a string would fail:
```typescript
const data = [{ category: 'fruit', name: 'apple' }];
const result = groupBy(data, item => item.category);
// This throws TypeError: Cannot convert object to …
```

fix(groupBy): preserve Object prototype method

---

docs/ja/reference/function/asyncNoop.md
docs/ko/reference/function/asyncNoop.md
docs/reference/function/asyncNoop.md
docs/zh_hans/reference/function/asyncNoop.md
src/function/asyncNoop.spec.ts
src/function/asyncNoop.ts
src/function/index.ts

issue: https://github.com/toss/es-toolkit/issues/636

feat(asyncNoop): add asyncNoop

---

src/compat/index.ts

Upgraded to `v1.30.1` and saw the changelog saying that `reverse` was now available in `es-toolkit/compat`. However, when I went to use it, I got the following error:
```
"reverse" is not exported by "../../node_modules/es-toolkit/dist/compat/index.mjs", imported by "src/components/..."
```

fix(reverse): Export reverse from compat barrel file

---

benchmarks/performance/pull.bench.ts
src/array/pull.ts

Reduce time complexity of `pull` from O($n^2$) to O(n).
Benchmark with lodash: 
Benchmark with old implementation: https://stackblitz.com/edit/vitest-dev-vitest-1rmnz8?file=pull.bench.ts

perf(pull): faster `pull`

---

src/compat/object/mergeWith.spec.ts
src/compat/object/mergeWith.ts

fix(merge): should work with nullish variables

---

.scripts/postbuild.sh
package.json
tests/check-dist.spec.ts

Adds handling for `error` packages that are missing during the build process. 
Also modifies `package.json` to ensure smooth [SubPath](https://nodejs.org/api/packages.html#subpath-exports) is applied.
I'm wondering if I'm missing handling for the `error` package, or if this is intentional?
I think this should be added since we provide documentation and modules for the `error` package in terms of libraries. 
docs: https://es-toolkit.slash.page/reference/error/AbortError.html
<br />
This will create the `src/error.d.ts` file, which will also create an `index` file inside the `error` folder.

chore: add error package build handling and updated package.json

---

docs/ja/reference/object/flattenObject.md
docs/ko/reference/object/flattenObject.md
docs/reference/object/flattenObject.md
docs/zh_hans/reference/object/flattenObject.md
src/object/flattenObject.spec.ts
src/object/flattenObject.ts

This PR adds a new `delimiter` parameter to the `flattenObject` utility function, allowing users to specify a custom separator for flattened object keys. The default delimiter remains '.' for backward compatibility.
At @lunit-io we wanted to flatten an object into a JSONPath compatible version with `flattenObject`. This required the delimeter to be a `/`, but the current impl did not support this use case.
Handling duplicate cases are out-of-scope of this library, thus not included here.
- Added optional `delimiter` parameter to `flattenObject` function signature
- Updated implementation to use the custom delimiter when joining nested keys
- Added comprehensive test cases for various delimiter scenarios
- Updated documentation in multiple languages (EN, JA, KO, ZH)
1. …

(feature) Add Custom Delimiter Support to flattenObject Utility

---

package.json

Hello. Thanks for great library. 
I'm currently using `es-toolkit` on react native side. 
`package exports` features are still [unstable & beta](https://reactnative.dev/blog/2023/06/21/package-exports-support) for default react native setups. 
By exposing "react-native" entry in package.json solves this [issue](https://github.com/toss/es-toolkit/issues/471). 
Otherwise, we have to edit `babel.config.js` manually like below or create patch files 
```ts
[
'module-resolver',
{
root: ['./'],
extensions: [
'.ios.ts',
'.android.ts',
'.ts',
'.ios.tsx',
'.android.tsx',
'.tsx',
'.jsx',
'.js',
'.json',
],
alias: {
'es-toolkit': './node_modules/es-toolkit/dist/index.js',
},
},
],
```
Thanks!

build: fix package exports on react native

---

src/object/flattenObject.ts

fix typo in `src/object/flattenObject.ts`

docs: fix typo in flattenObject

---

docs/ko/reference/predicate/isJSON.md
docs/reference/predicate/isJSON.md
src/predicate/isJSON.spec.ts
src/predicate/isJSON.ts

Added a new utility function `isJSON` that checks if a given value is a valid JSON string. This function also acts as a TypeScript type predicate, helping with type narrowing in TypeScript code.
- Function takes any value (`unknown` type) as input
- Returns `boolean` indicating if the string can be parsed as valid JSON
- Implements type predicate functionality (`value is string`)
- Uses try/catch with native `JSON.parse()` for validation
- Handles edge cases like JSON primitives ('null', 'true', etc.)
```typescript
import { isJSON } from 'es-toolkit/predicate';
// Valid JSON strings
isJSON('{"name":"John","age":30}')  // true
isJSON('[1,2,3]')                  // true
isJSON('true')                     // true (JSON primitive)
isJSON('null')                     // true (JSON primitive) …
```

feat(predicate): Add isJSON utility function

---

src/compat/index.ts
src/compat/math/maxBy.spec.ts
src/compat/math/maxBy.ts

I implemented the `maxBy` function to compat, which behaviors similar to Lodash's `maxBy`.
The function finds the element in an array with the maximum value based on a given iteratee, which can be:
- function returning a numeric value
- string representing a property key
- [key, value] pair for property matching
- partial object for deep property matching
Unit tests covering various edge cases have also been added.
Thanks to: #948

feat(compat): Implement compat/maxBy

---

src/compat/index.ts
src/compat/object/pickBy.spec.ts
src/compat/object/pickBy.ts

I added the `pickBy` function to compat, which behaviors similar to Lodash's `pickBy`:
the second param of the function is optional.
Thanks to: #946

feat(compat): Implement compat/pickBy

---

.github/CODEOWNERS

Gratefully, to support the rapid growth of es-toolkit, @raon0211 suggested closer collaboration!
Accordingly, my name(@dayongkr) is being added to `CODEOWNERS` to gain code review privileges and review code alongside @raon0211.

chore:  add `dayongkr` to `CODEOWNERS`

---

docs/.vitepress/en.mts
docs/.vitepress/ja.mts
docs/.vitepress/ko.mts
docs/.vitepress/zh_hans.mts

ES Toolkit Docs has the navigation links that allow users to access each category. Currently, clicking on the Reference tab redirects to the [Chunk](https://es-toolkit.slash.page/reference/array/chunk.html) page, which is the third item in the Reference category. This behavior is unexpected and may confuse users.
To improve usability, I’ve updated the links to direct users to the first subpage in the category, which is the [at](https://es-toolkit.slash.page/reference/array/at.html) page. This ensures a more intuitive navigation experience.

docs: edit link when clicking reference tab in nav

---

benchmarks/performance/meanBy.bench.ts
src/compat/index.ts
src/compat/math/meanBy.spec.ts
src/compat/math/meanBy.ts

close https://github.com/toss/es-toolkit/issues/1019

feat(compat): implement meanBy

---

benchmarks/performance/functionsIn.bench.ts
docs/ja/reference/compat/object/functionsIn.md
docs/ko/reference/compat/object/functionsIn.md
docs/reference/compat/object/functionsIn.md
docs/zh_hans/reference/compat/object/functionsIn.md
src/compat/index.ts
src/compat/object/functionsIn.spec.ts
src/compat/object/functionsIn.ts

close #1037
> 🚧 Since there is no official test case for `functionsIn` in Lodash, so I referred to [`functions`](https://github.com/lodash/lodash/blob/v5-wip/test/functions.spec.js) in Lodash instead.

feat(functionsIn): Add `functionsIn` to compat/object

---

docs/.vitepress/components/Sandpack.vue

In a component using `Sandpack`, when the dark theme is enabled, there's an issue where the `color-scheme` is applied as light instead of dark.
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
<tr>
<td align="center">
Before
</td>
<td align="center">
After
</td>
</tr>
</table>

fix(docs): update dark theme `color-scheme` for `Sandpack`

---

benchmarks/performance/unionBy.bench.ts
benchmarks/performance/unionWith.bench.ts
src/compat/array/unionBy.spec.ts
src/compat/array/unionBy.ts
src/compat/array/unionWith.spec.ts
src/compat/array/unionWith.ts
src/compat/index.ts

feat(unionBy, unionWith): add `unionBy`, `unionWith` to `compat/array`

---

src/compat/array/keyBy.spec.ts
src/compat/array/keyBy.ts

Resolves:  #1007
Implemented compact/keyBy as described in #1007
I included the lodash test cases provided in the issue, along with a few additional ones.

feat(keyBy): Implement compact/keyBy

---

benchmarks/performance/zipObject.bench.ts
src/compat/array/unzip.ts
src/compat/array/zipObject.spec.ts
src/compat/array/zipObject.ts
src/compat/array/zipObjectDeep.spec.ts
src/compat/index.ts

feat(compat): implement zipObject

---

src/compat/array/shuffle.spec.ts
src/compat/array/shuffle.ts

Resolves:  #1011 
Implemented compact/shuffleas described in #1011 
I included the lodash test cases provided in the issue, along with a few additional ones.

feat(shuffle): Implement compact/shuffle

---

docs/ja/reference/function/retry.md
docs/ko/reference/function/retry.md
docs/reference/function/retry.md
docs/zh_hans/reference/function/retry.md
src/function/retry.spec.ts
src/function/retry.ts

adds support for customizing the retry delay based on the current attempt count via a user-defined function.
This work continues from the discussion in [#940](https://github.com/toss/es-toolkit/pull/940), where we explored adding jitter/backoff strategies while keeping the implementation simple.
* RetryOptions.delay now accepts a function (attempts: number) => number
* Test cases updated to verify behavior with both fixed and dynamic delays
* Used performance.now() in tests for more accurate delay measurements

feat(retry-custom-delay): add support for custom delay function based on attempts

---

src/compat/_internal/mapToEntries.ts
src/compat/_internal/setToEntries.ts
src/compat/object/toPairs.ts
src/compat/object/toPairsIn.ts

For `Map` and `Set`, I improved the performance of `toPairs/toPairsIn` with better logic than converting to `entries` via `Array.from(obj.entries())`.
This logic pre-allocates an array and uses Iterator values.

perf(toPairs): improve performance by pre-allocating array and using iterator values

---

docs/ko/reference/compat/object/extend.md

The example of the `extend` function is incorrect.

docs(extend): fix typo

---

benchmarks/performance/ary.bench.ts

Added the missing benchmark for the ary function from es-toolkit in ary.bench.ts

feat(bench): add vitest benchmark for ary function

---

src/compat/array/keyBy.ts
src/compat/array/xorBy.ts
src/compat/function/debounce.ts
src/compat/function/throttle.spec.ts

When `throttleMs` is set to 0, lodash's `_.throttle` immediately invokes the throttled function. 
Previously, `es-toolkit/compat` behaved differently in this scenario. This change adjusts the condition to match lodash's immediate invocation for throttleMs = 0, ensuring compatibility.

fix(throttle): Align `throttle` behavior with lodash when `throttleMs` is 0.

---

benchmarks/performance/invokeMap.bench.ts
docs/ja/reference/compat/array/invokeMap.md
docs/ko/reference/compat/array/invokeMap.md
docs/reference/compat/array/invokeMap.md
docs/zh_hans/reference/compat/array/invokeMap.md
src/compat/array/invokeMap.spec.ts
src/compat/array/invokeMap.ts
src/compat/compat.ts

close #1006
> The testcases follow [lodash.invokeMap](https://github.com/lodash/lodash/blob/v5-wip/test/invokeMap.spec.js).

feat(compat): add `invokeMap` to compat/array

---

docs/index.md

Ref: https://discord.com/channels/1281071127052943361/1281085859608924282/1368947219918749857
This PR fixes the hard-coded reference URL to latest one.

docs(index): Fix hard-coded reference url

---

benchmarks/performance/clone.bench.ts
benchmarks/performance/cloneWith.bench.ts
docs/ja/reference/compat/object/cloneWith.md
docs/ko/reference/compat/object/cloneWith.md
docs/reference/compat/object/cloneWith.md
docs/zh_hans/reference/compat/object/cloneWith.md
src/compat/compat.ts
src/compat/object/clone.spec.ts
src/compat/object/clone.ts
src/compat/object/cloneWith.spec.ts
src/compat/object/cloneWith.ts

close #1017 close #1022
> The testcases follow [lodash.clone](https://github.com/lodash/lodash/blob/v5-wip/test/clone-methods.spec.js).
---

feat(compat): add `clone`, `cloneWith` to compat/object

---

benchmarks/bundle-size/find.spec.ts
benchmarks/performance/toCamelCaseKeys.bench.ts

This PR improves the naming consistency in the benchmark files to enhance code readability and maintainability.
1. Fixed test name inconsistency in `benchmarks/bundle-size/find.spec.ts` - The test was labeled as 'es-toolkit' but was actually testing 'es-toolkit/compat'. This has been corrected for consistency with other benchmark files.
2. Improved function naming in `benchmarks/performance/toCamelCaseKeys.bench.ts` - Renamed `toCamelCaseKeysLodash` to `toCamelCaseKeysWithLodashFp` to more accurately describe what the function does, avoiding confusion that it might be a native lodash function.
N/A

fix(find.spec, toCamelCaseKeys.bench): Improve test names and function naming

---

docs/.vitepress/data/bannerData.ts

Fixed a bug where clicking the `frontend-fundamentals` link from the floating banner at the bottom right of the page on https://es-toolkit.slash.page/ would lead to a 404 page when the site locale was set to English.

docs: fix wrong url 

---

src/compat/object/findKey.ts

Fix a typo in the `findKey` function's type annotation (`Partail` → `Partial`).

fix(findKey): correct typo 'Partail' to 'Partial' in type annotation

---

.scripts/postbuild.sh
package.json

Although the main environment is CommonJS (CJS), since some environments like testing use ESM, we're adding ESM files under the compat/* path to support dual module paths.

feat(scripts): add support for .mjs and .d.mts exports in compat module

---

docs/ja/reference/function/before.md
docs/ko/reference/function/before.md

Fixed incorrect documentation example in the before function that was showing after function usage instead of proper before function examples.
(close #1246)

docs(before): update examples to use 'before' function instead of 'after' function

---

.github/CONTRIBUTING-ko_kr.md
README-ko_kr.md

This PR adds a Korean translation of the `CONTRIBUTING.md` file and updates the Korean README to link to the new Korean contributing guide, making it easier for Korean-speaking developers to contribute to es-toolkit.
- **Created** `.github/CONTRIBUTING.ko.md` with Korean translation of the contributing guidelines
- **Updated** `README-ko_kr.md` to link to the new Korean contributing guide
- Used natural Korean expressions rather than literal translations
- Maintained technical accuracy while ensuring readability
- Applied consistent terminology throughout the document
- Preserved all original links, code examples, and formatting
- Used "해요체" for friendly and approachable tone

docs(contributing): add Korean version of contributing guidelines

---

docs/reference/compat/util/uniqueId.md
docs/zh_hans/reference/compat/util/uniqueId.md

This PR fixes incorrect function titles in the English and Simplified Chinese documentation for the `uniqueId` function.
In both translations, the title did not match the function being documented:
- English doc: `# constant` → `# uniqueId`
- Simplified Chinese doc: `# toString` → `# uniqueId`
- Updated the function title in the English doc from `# constant` to `# uniqueId`.
- Updated the function title in the Simplified Chinese doc from `# toString` to `# uniqueId`.
- Verified that the rest of the content, signature, parameters, returns, and examples already correctly describe `uniqueId`.

fix: Fix incorrect function titles in uniqueId docs

---

docs/ko/reference/compat/object/extendWith.md
docs/reference/compat/object/extendWith.md
docs/zh_hans/reference/compat/object/extendWith.md

This PR fixes an error in the `extendWith` documentation examples (`en`, `ko`, `zh_hans`).  
The current examples incorrectly call `assignInWith` instead of `extendWith`.
- Replaced `assignInWith` with `extendWith` in all `extendWith` examples.
- Applied the change consistently across English, Korean, Chinese

fix: incorrect function name in extendWith examples

---

docs/ja/reference/compat/array/findLast.md
docs/reference/compat/array/findLast.md

This PR fixes incorrect examples in the English and Japanese documentation for the `findLast` function.  
The current examples incorrectly import and call `find` instead of `findLast`.
- Replaced all `find` imports and calls with `findLast` in English and Japanese `findLast` documentation examples.
- Updated array and object usage examples to correctly demonstrate `findLast` behavior.

fix: incorrect findLast examples in English and Japanese docs

---

docs/ja/reference/compat/array/some.md
docs/ko/reference/compat/array/some.md
docs/reference/compat/array/some.md
docs/zh_hans/reference/compat/array/some.md

This PR addresses issues in the documentation examples for the `some` function, making them consistent and executable as intended.
1. Korean documentation (`ko`):
- Replaced incorrect `every` calls with `some` in both array and object examples.
- Updated expected outputs in the object examples to match the actual behavior of `some`.
2. All language documentation (`en`, `ko`, `zh_hans`, `zh_hant`):
- Fixed variable name mismatches in examples where `obj` was declared but `object` was used in function calls.

fix: some function example issues in Korean docs and variable name mismatches in all languages

---

docs/ja/reference/compat/array/each.md
docs/ko/reference/compat/array/each.md

This PR fixes incorrect example output for the `each` function in the documentation.
Currently, the output is `[3, 2, 1]`, but based on the provided loop logic, the correct value should be `[1, 2, 3]`.
Additionally, the `import` statement has been updated to use the correct module path.
- Corrected the output of the Korean and Japanese documentation examples from `[3, 2, 1]` to `[1, 2, 3]`.
- Updated the `import` path in the Korean and Japanese documentation example from `es-toolkit/compat` to `es-toolkit/array`.
---
💬 Note: The Korean/Japanese and English/Chinese documentation currently use different example code for the `each` function.
Do you think the two examples should be aligned for consistency in a future update?

fix: correct wrong output in each function example

---

docs/ja/reference/array/sortBy.md
docs/ko/reference/array/sortBy.md
docs/reference/array/sortBy.md
docs/zh_hans/reference/array/sortBy.md
src/array/sortBy.ts

This PR updates the `sortBy` function example data in all documentation languages (`en`, `ko`, `zh_hans`, `zh_hant`) to remove unintended trailing spaces in the `user` property.  
The extra spaces caused the actual sort result to differ from the expected example output, which could confuse readers.
- Removed trailing spaces from `'bar '` → `'bar'`
- Removed trailing spaces from `'foo '` → `'foo'`
- Applied this change consistently across all translations to ensure identical execution results.

fix: remove trailing spaces in sortBy function example

---

docs/ko/reference/compat/array/forEach.md
docs/reference/compat/array/forEach.md

This pull request updates the forEach documentation to correct examples, fix type annotations, and improve parameter descriptions for clarity and accuracy.
- Fixed import path in example code from `es-toolkit/array` to `es-toolkit/compat`.
- Corrected array iteration output in example from `[3, 2, 1]` to `[1, 2, 3]`.
- Updated `key` parameter type in function signature from `T` to `keyof T`.
- Simplified the `object` parameter description for conciseness and readability.

Fix: correct forEach example import path, parameter type, and description in documentation

---

src/object/toCamelCaseKeys.ts
src/object/toSnakeCaseKeys.ts

Rename loop-local variables from plural to singular to avoid implying a collection. This is a readability-only change; no behavior, public API, or types are affected.
- src/object/toCamelCaseKeys.ts
- camelCaseKeys → convertedValue
- src/object/toSnakeCaseKeys.ts
- snakeCaseKeys → convertedValue
Each loop iteration stores a single transformed value. Singular naming better communicates the intent and avoids confusion.
- No behavior change
- No public API/type changes
- No docs updates required
- No bundle-size impact
- Typecheck passed
- Unit tests for both files passed
---
Notes:
First-time open source contribution. Feedback welcome!
Korean summary:
루프에서 단일 값을 담는 로컬 변수를 복수형에서 단수형으로 바꿔 가독성을 개선했어요. 동작/공개 API/타입 변화는 없습니다. 타입체크와 테스트 통과했습니다.

fix: rename loop-local variables to singular in toCamelCaseKeys and toSnakeCaseKeys

---

src/string/pascalCase.spec.ts

Replaces `"PascalCase"` w/ `"pascalCase"` to be consistent with other specs in the repo.

chore(tests): fixes inconsistent capitalization in test suite description

---

src/object/cloneDeepWith.ts

I'm unable to use cloneDeepWith in my mini-program. It fails in runtime environments that do not support Blob. Although src/predicate/isBlob.ts provides compatibility for environments without Blob support, the cloneDeepWith function itself does not have this compatibility.

fix(cloneDeepWith): fix runtime error in environments without Blob support

---

docs/ja/reference/compat/string/split.md
docs/ko/reference/compat/string/split.md
docs/reference/compat/string/split.md
docs/zh_hans/reference/compat/string/split.md

This PR updates the return type description in the documentation for the `split` function.  
Previously, the return type was described as `Array`, which is less specific and inconsistent with the interface signature.
- Changed the return type description from `Array` to `string[]` in all language documents.
- This clearly indicates that the function returns an array of strings.
- Improved the consistency between the documentation and the TypeScript interface signatures.

fix(split): Update split docs return type to string[] for consistency with interface

---

docs/ko/reference/compat/string/endsWith.md
docs/reference/compat/string/endsWith.md
docs/zh_hans/reference/compat/string/endsWith.md

This PR fixes the incorrect return type in the documentation for the `endsWith` function.  
The original docs mistakenly specify the return type as `string` while the actual function returns a `boolean`.
- Updated the function signature to:
```ts
function endsWith(str: string, target: string, position: number = 0): boolean;
```
- This update was applied to Korean, English, and Simplified Chinese (`zh_hans`) documentation only. The Japanese documentation was already correct.

fix: Fix endsWith docs return type from string to boolean

---

docs/ja/reference/predicate/isNil.md
docs/ko/reference/predicate/isNil.md
docs/reference/predicate/isNil.md
docs/zh_hans/reference/predicate/isNil.md

This PR updates the `isNil` documentation across all translations to include missing parameter and return descriptions.  
Previously, the docs only contained the interface and examples, but did not explicitly describe the function's parameter or return value.
- Added a "Parameters" section explaining:
- `x` (`unknown`): The value to check.
- Added a "Returns" section explaining:
- `(x is null | undefined)`: Returns `true` if the value is `null` or `undefined`, otherwise `false`.
- Applied the same update consistently across all language versions (`en`, `ko`, `zh_hans`, `zh_hant`).
This ensures the `isNil` documentation is complete, consistent, and aligns with other predicate function docs.

fix: Add missing parameter and return descriptions to isNil docs

---

docs/ja/reference/compat/predicate/isInteger.md
docs/ko/reference/compat/predicate/isInteger.md
docs/reference/compat/predicate/isInteger.md
docs/zh_hans/reference/compat/predicate/isInteger.md

This PR corrects the return type description of the `isInteger` function in all documentation translations (`en`, `ko`, `zh_hans`, `zh_hant`).
Previously, the docs stated the return type as `boolean`.  
In TypeScript, `isInteger` is a type guard, so the proper return type is `value is number`.
- Updated the return type description in all languages:
- Incorrect: (`boolean`)
- Correct: (`value is number`)
- Ensured that the narrative explanation still clarifies: returns `true` if the value is an integer, otherwise `false`.

fix: Fix incorrect return type of isInteger docs

---

docs/ja/reference/predicate/isFunction.md
docs/ko/reference/predicate/isFunction.md

This PR fixes incorrect return type descriptions in the Korean and Japanese documentation for the `isFunction` function.  
Both docs incorrectly stated the return type as `value is number`.
- Updated the return type in Korean and Japanese docs:
- Incorrect: (value is number)
- Corrected: (value is (...args: never[]) => unknown)
- Ensured the description now matches the actual TypeScript interface and type guard behavior.

fix: Fix incorrect return type description for isFunction docs

---

docs/ja/reference/compat/array/each.md
docs/ko/reference/compat/array/each.md
docs/reference/compat/array/each.md

This PR fixes a documentation error in the `each` function for the English and Korean docs.  
The `callback` parameter type for the key was incorrectly documented as `T` instead of `keyof T`.
- Updated the `callback` parameter type in English and Korean docs:
- Incorrect: `(value: T[keyof T], key: T, object: T)`
- Corrected: `(value: T[keyof T], key: keyof T, object: T)`
- Adjusted the parameter description so that:
- `key` is described as the **current element's key (index or property name)**, matching the actual function signature.
This change aligns the documentation with the correct TypeScript definition and clarifies the role of the `key` parameter.
Additionally, updated the callback parameter names in the examples to match the interface.(`ko`, `en`, `ja`)

fix: Fix incorrect callback key parameter type in each docs

---

docs/ja/reference/array/fill.md
docs/ko/reference/array/fill.md
docs/reference/array/fill.md
docs/zh_hans/reference/array/fill.md

This PR updates the `fill` function documentation in all translations (`en`, `ko`, `zh_hans`, `zh_hant`) to ensure the interface signatures are consistent with the implementation's JSDoc definition.
Previously, the `fill` interfaces in the docs used inconsistent or incorrect generic type parameters (`value` as `T` instead of `U`, `array` not matching with `Array<T | U>`). This caused confusion when comparing the docs with the implementation.
- Updated the `fill` interface in all language docs:
- `array` is now `Array<T | U>`
- `value` is now `U`
- Return type is `Array<T | U>`
- Ensured parameter descriptions and return types match the corrected signature.
- Maintained consistency across English, Korean, Simplified Chinese, and Traditional Chinese docs.
Corrected interface now looks like …

fix: Align fill docs interface with implementation JSDoc across 

---

docs/ja/reference/compat/util/toFinite.md
docs/ko/reference/compat/util/toFinite.md
docs/reference/compat/util/toFinite.md
docs/zh_hans/reference/compat/util/toFinite.md
src/compat/util/toFinite.ts

This pull request fixes a typo where `toFinite` function examples were incorrectly labeled as `toNumber` in both the JSDoc comments and the official documentation.
- Replaced all occurrences of `toNumber` with `toFinite` in the examples within JSDoc comments.
- Corrected method name references in the official documentation/tutorials to reflect toFinite usage.
- No changes were made to example outputs or function implementations.
```ts
toNumber(3.2); // => 3.2
toNumber(Number.MIN_VALUE); // => 5e-324
toNumber(Infinity); // => 1.7976931348623157e+308
toNumber('3.2'); // => 3.2
toNumber(Symbol.iterator); // => 0
toNumber(NaN); // => 0
```
```ts
toFinite(3.2); // => 3.2
toFinite(Number.MIN_VALUE); // => 5e-324
toFinite(Infinity); // => 1.7976931348623157e+308
toFinite('3.2'); // => 3.2 …
```

Fix: correct method name from toNumber to toFinite in JSDoc and official documentation

---

docs/ja/reference/array/zipObject.md
docs/ja/reference/compat/array/zipObjectDeep.md
docs/ko/reference/array/zipObject.md
docs/ko/reference/compat/array/zipObjectDeep.md
docs/reference/array/zipObject.md
docs/reference/compat/array/zipObjectDeep.md
docs/zh_hans/reference/array/zipObject.md
docs/zh_hans/reference/compat/array/zipObjectDeep.md

This PR improves the documentation for `zipObject` and `zipObjectDeep` by aligning their TypeScript generics and return types with other related documents:
- Modified the generic constraint from `P extends string | number | symbol` to `P extends PropertyKey` for clarity and uniformity.
- Updated the return type from mapped type `{ [K in P]: V }` to `Record<P, V>` to improve readability and maintain consistency across documents.
These changes enhance the clarity and uniformity of the documentation, making it easier to read and understand for users.

docs: Update zipObject and zipObjectDeep docs to use PropertyKey and Record for better readability

---

docs/ja/reference/math/range.md
docs/ko/reference/math/range.md
docs/reference/math/range.md
docs/zh_hans/reference/math/range.md
src/compat/math/range.ts

This PR enhances the documentation for the `range` function by adding an error section to clarify behavior when `step` is 0.
- Previously, the documentation did not specify any error for a `step` value of 0.
- The documentation has been updated with a new **Error** section stating that:
- Providing a `step` value of 0 will result in an error being thrown.
This update improves the clarity and reliability of the function's usage guidance.

docs: Add error handling documentation for zero step value in range function

---

docs/ja/reference/compat/array/reduce.md
docs/ja/reference/compat/array/reduceRight.md
docs/ko/reference/compat/array/reduce.md
docs/ko/reference/compat/array/reduceRight.md
docs/reference/compat/array/reduce.md
docs/reference/compat/array/reduceRight.md
docs/zh_hans/reference/compat/array/reduce.md
docs/zh_hans/reference/compat/array/reduceRight.md

This PR updates the documentation for both `reduce` and `reduceRight` functions by replacing broad `any` types with more precise generic types (`T` and `U`).  
- Updated `collection` type to include `Record<PropertyKey, T>` for object collections.
- Changed `iteratee` function parameter and return types from `any` to generic `U` for the accumulator, and `T` for value.
- Changed `initialValue` type from `any` to generic `U`, marking it as optional.
- Clarified the return type as `U`, explaining that if `initialValue` is omitted, the return type is the element type `T`.
Using generic types improves type safety and better reflects the functions' TypeScript signatures and runtime behavior. The previous `any` types were too broad and could cause confusion or loss of type information.
These …

fix: Update reduce and reduceRight docs to use generic types for iteratee, initialValue, and return

---

docs/ja/reference/string/capitalize.md
docs/ko/reference/string/capitalize.md
docs/reference/string/capitalize.md
docs/zh_hans/reference/string/capitalize.md

This PR updates the documentation for the `capitalize` function to provide clearer and more precise descriptions:
- The parameter `str` is described as the string to be transformed, using the generic type `T`.
- The return value is described as `Capitalize<T>`, indicating the string with the first character capitalized and the rest converted to lowercase.
- These descriptions better reflect the TypeScript interface and function behavior with clear and concise language.
- Updated the parameter section to:
- `str` (`T`): The string to be transformed.
- Updated the return value section to:
- (`Capitalize<T>`): The string with the first letter capitalized and the rest in lowercase.

docs: Simplify and clarify capitalize function parameter and return value descriptions

---

docs/ja/reference/compat/util/stubFalse.md
docs/ja/reference/compat/util/stubTrue.md
docs/ko/reference/compat/util/stubFalse.md
docs/ko/reference/compat/util/stubTrue.md
docs/reference/compat/util/stubFalse.md
docs/reference/compat/util/stubTrue.md
docs/zh_hans/reference/compat/util/stubFalse.md
docs/zh_hans/reference/compat/util/stubTrue.md

This PR updates the documentation for the `stubFalse` and `stubTrue` functions to reflect their precise return types.  
Both functions always return a constant literal value (`false` and `true` respectively), so the return types are changed from the broad `boolean` to the literal types `false` and `true`.  
- Changed `stubFalse` return type from `boolean` to `false`.
- Changed `stubTrue` return type from `boolean` to `true`.

fix: Update stubFalse and stubTrue docs to use literal return types false and true

---

docs/ja/reference/predicate/isString.md
docs/ko/reference/predicate/isString.md
docs/reference/predicate/isString.md
docs/zh_hans/reference/predicate/isString.md

This PR updates the return type description of the `isString` function in the documentation to match the TypeScript interface exactly.
```typescript
function isString(value: unknown): value is string;
```
- Changed from:
(`x is string`): Returns true if the value is a string, false otherwise.
- To:
(`value is string`): Returns true if the value is a string, false otherwise.
This change improves consistency between the interface and documentation, reducing potential confusion.

docs: Update isString docs return type from `x is string` to `value is string`

---

docs/ko/reference/predicate/isNotNil.md

This PR updates the parameter description for the `isNotNil` function in the documentation.  
The previous description was:
- 값null이나 undefined가 아님을 확인할 값.
This phrase was slightly awkward and inconsistent with other docs, which use a more concise phrasing.  
- Revised the parameter description to:
- `null`이나 `undefined`가 아님을 확인할 값.
- This change improves clarity and aligns the style with other documentation entries.

docs: Rephrase isNotNil docs parameter description for better clarity

---

src/compat/object/unset.spec.ts
src/compat/object/unset.ts

- resolve #1320 
- remove `defaultValue` from `get()`, because it leads unwanted result when path is not matching on object.
- instead, use ternary operator for handling the case that `path.slice(0, -1)` return empty array.
- add a test `"does not delete root properties from nonexistent paths" `

fix(compat/unset): Fix logic bug with nonexistent paths

---

src/compat/object/omit.spec.ts
src/compat/object/omit.ts

Some of our tests fail when using `import { omit } from 'es-toolkit/compat'` instead of `import { omit } from 'lodash'`. While investigating this, I found several incompatibilities with between es-toolkit and Lodash. I'm happy to open a PR to try and address these, but the various combinations and corner cases get tricky enough that I wanted guidance on the extent to which full Lodash compatibility is desired - Lodash's behavior seems odd in places. To the best of my ability, here's how compatibility currently works:
* Deep properties: Both Lodash and es-toolkit/compat allow omitting deep properties. E.g.: `omit({ a: { b: { one: 1, two: 2 }}, 'b.one')`.
* Deep vs. shallow copy: Lodash performs a deep copy (but not identical to `cloneDeep` - see below) if it detects that you're omitting …

fix(omit): Avoid unnecessary deep cloning in `omit`

---

src/compat/array/findIndex.ts

[Tests](https://github.com/toss/es-toolkit/blob/main/src/compat/array/findIndex.spec.ts) and [implementation](https://github.com/toss/es-toolkit/blob/main/src/compat/array/findIndex.ts) show that `findIndex` returns -1 when no match is found, but the JSDoc incorrectly documented `undefined`. 
This commit fixes the JSDoc.

fix(findIndex): correct JSDoc return type to -1 instead of undefined

---

src/compat/array/dropRightWhile.spec.ts

test(compat/array/dropRightWhile): add test case for 'identity' function default 'predicate'
