.vscode/settings.json

I want to reduce these kind of Pull Request(https://github.com/toss/es-toolkit/pull/14) by this change.
After this change, we force feature "format on save" in contributors' vscode

chore(.vscode): Turn on format on save as default

---

docs/ko/reference/array/uniqBy.md
docs/ko/reference/array/uniqWith.md
docs/ko/reference/math/maxBy.md
docs/ko/reference/math/minBy.md
docs/ko/reference/object/omitBy.md
docs/reference/array/uniqBy.md
docs/reference/array/uniqWith.md
docs/reference/math/maxBy.md
docs/reference/math/minBy.md
docs/reference/object/omitBy.md
src/array/differenceWith.ts
src/array/dropWhile.ts
src/array/intersectionWith.ts
src/array/unionWith.ts
src/array/xorWith.ts
src/array/zip.ts
src/array/zipWith.ts
src/math/maxBy.spec.ts
src/math/minBy.spec.ts
src/math/minBy.ts

While reviewing the codebase, I noticed that some files weren't formatted with Prettier, so I ran the formatting script.

style(*): apply formatting

---

docs/reference/array/minBy.md

change the returns : { a : 3 } to { a : 1 }

fix the minBy example

---

src/math/sum.ts

Converted `for of` loop to indexed `for` loop for better performance.
NodeJS v20.10.0:
Browser (`Brave Version 1.67.123 Chromium: 126.0.6478.126 (Official Build) (arm64)`):
```js
// src/helpers.ts
var measureTime = (fn) => {
const start = performance.now();
fn();
const end = performance.now();
return end - start;
};
// src/index.ts
var sumForLoop = (arr) => {
let sum = 0;
for (let i = 0; i < arr.length; i++) {
sum += arr[i];
}
return sum;
};
var sumForOf = (arr) => {
let sum = 0;
for (const num of arr) {
sum += num;
}
return sum;
};
function measureTimes(arrayToSum) {
const forLoop = measureTime(() => sumForLoop(arrayToSum));
const forOf = measureTime(() => sumForOf(arrayToSum));
return { forLoop, forOf };
}
function measureAll() {
const arraySizes = [1e3, 1e4, 1e5, 1e6, 1e7, 1e8];
const …
```

perf(sum): Improve performance of sum

---

docs/reference/string/kebabCase.md

fix: changed text `kebab_case` to `kebab-case`

fix: casing for kebab_case text

---

docs/.vitepress/ko.mts

Thank you for your hard work @raon0211, 
While looking at the document by chance, I found that the links to the Korean get and set sections were incorrectly entered. So I edited it and uploaded it.

chore(ko-docs-sidebar): ko-object-sidebar get,set link fix

---

docs/compatibility.md
src/array/tail.ts
src/compat/array/head.spec.ts
src/compat/array/tail.spec.ts
src/compat/index.ts

Add the lodash tests for both `head` and `tail` following this guideline https://github.com/toss/es-toolkit/issues/235:
- `head`: https://github.com/lodash/lodash/blob/6a2cc1dfcf7634fea70d1bc5bd22db453df67b42/test/head.spec.js#L1
- `tail`: https://github.com/lodash/lodash/blob/6a2cc1dfcf7634fea70d1bc5bd22db453df67b42/test/tail.spec.js#L1

chore(head,tail): Add lodash tests

---

docs/compatibility.md
docs/ko/compatibility.md
docs/zh_hans/compatibility.md
src/compat/array/fill.spec.ts
src/compat/array/fill.ts
src/compat/index.ts

I add a testcase based on [lodash/fill](https://github.com/lodash/lodash/blob/main/test/fill.spec.js) for compatibility at first, but it failed.
So I add a coercing integer by using `Math.floor` and add a converting to 0 from falsy value.
close #257

feat(fill): Add compatibility with lodash

---

docs/compatibility.md
docs/ko/compatibility.md
docs/zh_hans/compatibility.md
src/compat/object/invert.spec.ts

There are no fails. So I just add a test case and update compatibility docs.
close #260

test(invert): add compatibility test case

---

docs/ko/reference/array/minBy.md
src/array/minBy.spec.ts

docs - minBy : Returns "3" -> "1"
test - minBy : describe "max" -> "min"

test - minBy : "max" -> "min",  docs - minBy : 3 -> 1

---

docs/.vitepress/en.mts
docs/.vitepress/ko.mts
docs/ko/reference/array/isSubset.md
docs/reference/array/isSubset.md
src/array/index.ts
src/array/isSubset.spec.ts
src/array/isSubset.ts

close: #193 
Add the isSubset function that was discussed.

feat(isSubset): Add isSubset function

---

benchmarks/performance/bind.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/zh_hans.mts
docs/reference/function/bind.md
docs/zh_hans/reference/function/bind.md
src/function/bind.spec.ts
src/function/bind.ts
src/function/index.ts

test case from https://github.com/lodash/lodash/blob/main/test/bind.spec.js, missing `chain` and `_.placeholder` related implementations.
benchmark:

feat(bind): implement bind

---

src/predicate/isLength.ts

- Add missing JSDocs type annotations on `isNull.ts`

style(isLength): add missing JSDoc

---

src/string/index.ts
src/string/pascalCase.spec.ts
src/string/pascalCase.ts

feat(pascalCase): implement pascalCase

---

src/compat/array/findIndex.spec.ts

chore: remove unused import

---

docs/ko/reference/compat/predicate/isArray.md
docs/reference/compat/predicate/isArray.md
docs/zh_hans/reference/compat/predicate/isArray.md

Fixed outdated docs for the `isArray` compat function.

docs(isArray): Update docs for `isArray`

---

README-ja_jp.md
README-ko_kr.md
README-zh_hans.md
README.md

I created Japanese translated README.

docs: add Japanese README

---

benchmarks/performance/forEachRight.bench.ts
benchmarks/performance/indexOf.bench.ts
benchmarks/performance/tail.bench.ts
src/array/sampleSize.ts
src/compat/predicate/isBoolean.ts
src/compat/predicate/isString.ts
src/predicate/isString.spec.ts
src/string/_internal/getWords.ts
src/string/capitalize.spec.ts

style: Fix typo

---

src/array/takeRightWhile.ts

I updated jsdoc for `takeRightWhile`

docs(takeRightWhile): fix docs for `takeRightWhile`

---

src/array/initial.ts

It would be great if `initial` support readonly array.

feat(initial): Support readonly array in `initial`

---

src/math/randomInt.spec.ts

I have corrected the inaccurate description.

docs(randomInt): Update test case description for `randomInt`

---

benchmarks/performance/isWeakSet.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/ja.mts
docs/.vitepress/ko.mts
docs/.vitepress/zh_hans.mts
docs/compatibility.md
docs/ja/compatibility.md
docs/ja/reference/predicate/isWeakSet.md
docs/ko/compatibility.md
docs/ko/reference/predicate/isWeakSet.md
docs/reference/predicate/isWeakSet.md
docs/zh_hans/compatibility.md
docs/zh_hans/reference/predicate/isWeakSet.md
src/compat/index.ts
src/compat/predicate/isWeakSet.spec.ts
src/compat/predicate/isWeakSet.ts
src/predicate/index.ts
src/predicate/isWeakSet.spec.ts
src/predicate/isWeakSet.ts

I added `isWeakMap` in es-toolkit and es-toolkit/compat.
And I also added the japan and chinese docs, by coping `isWeakMap` docs.

feat(isWeakSet): add `isWeakSet` with compatibility

---

benchmarks/performance/isTypedArray.bench.ts
src/predicate/isTypedArray.ts

for this issue https://github.com/toss/es-toolkit/issues/476

chore(isTypedArray): Change the implementation of isTypedArray

---

benchmarks/performance/escapeRegExp.bench.ts
docs/.vitepress/en.mts
docs/.vitepress/zh_hans.mts
docs/reference/string/escapeRegExp.md
docs/zh_hans/reference/string/escapeRegExp.md
src/string/escapeRegExp.spec.ts
src/string/escapeRegExp.ts
src/string/index.ts

feat(escapeRegExp): implement escapeRegExp

---

benchmarks/performance/debounce.bench.ts
benchmarks/performance/flattenDepth.bench.ts
benchmarks/performance/matchesProperty.bench.ts
benchmarks/performance/mergeWith.bench.ts
benchmarks/performance/noop.bench.ts
benchmarks/performance/pickBy.bench.ts
benchmarks/performance/throttle.bench.ts

fix(benchmark): add missing bench

---

benchmarks/performance/conforms.bench.ts
benchmarks/performance/conformsTo.bench.ts
docs/reference/function/conforms.md
docs/reference/function/conformsTo.md
docs/zh_hans/reference/function/conforms.md
docs/zh_hans/reference/function/conformsTo.md
docs/zh_hans/reference/function/memoize.md
src/compat/function/conforms.spec.ts
src/compat/function/conforms.ts
src/compat/function/conformsTo.spec.ts
src/compat/function/conformsTo.ts
src/compat/index.ts
src/function/conforms.spec.ts
src/function/conforms.ts
src/function/conformsTo.spec.ts
src/function/conformsTo.ts
src/function/index.ts

benchmark
I'm not sure this function should be implemented entirely in compat

feat(conforms/conformsTo): implement conforms&conformsTo

---

src/array/at.spec.ts

Added missing test case for negative indices

test(at): add negative indices test

---

docs/.vitepress/shared.mts

docs: add discord link to website

---

benchmarks/performance/parseInt.bench.ts
docs/reference/compat/string/parseInt.md
docs/zh_hans/reference/compat/string/parseInt.md
src/compat/index.ts
src/compat/string/parseInt.spec.ts
src/compat/string/parseInt.ts

feat(compat): implement parseInt

---

src/compat/string/capitalize.spec.ts

I added [lodash test case](https://github.com/lodash/lodash/blob/main/test/capitalize.spec.js) for capitalize.

feat(capitalize): Add lodash test case

---

benchmarks/performance/findLastIndex.bench.ts
docs/ja/reference/compat/array/findLastIndex.md
docs/ko/reference/compat/array/findLastIndex.md
docs/reference/compat/array/findLastIndex.md
docs/zh_hans/reference/compat/array/findLastIndex.md
src/compat/array/findLastIndex.spec.ts
src/compat/array/findLastIndex.ts
src/compat/index.ts

I implement findLastIndex.(resolve #502) I would appreciate any feedback and reviews.

feat(compat): implement findLastIndex

---

docs/ja/reference/function/spread.md
docs/ko/reference/function/spread.md
docs/reference/function/spread.md
docs/zh_hans/reference/function/spread.md

Documentation in other languages may also need to be modified

fix(spread): fix doc

---

src/array/initial.ts

I added function overloading signatures for `initial` similar to [`tail`](https://github.com/toss/es-toolkit/blob/main/src/array/tail.ts) and included corresponding examples to aid understanding.

feat(initial): Add overloaded signatures for `initial`

---

src/array/at.ts

perf(at): improve performance

---

src/function/partial.spec.ts
src/function/partialRight.spec.ts

In fact, partial and partialright have passed lodash's test completely!

test(partial): add curry test

---

benchmarks/performance/isNaN.bench.ts
docs/ko/reference/predicate/isNaN.md
docs/reference/predicate/isNaN.md
src/predicate/index.ts
src/predicate/isNaN.spec.ts
src/predicate/isNaN.ts

Hi there👋 I've implemented the isNaN function. 
I welcome any feedback for improvements. Thank you.

feat(isNaN): add `isNaN` function

---

docs/ja/reference/string/upperFirst.md
src/string/upperFirst.ts

- Fix incorrect result.
- Make formatting consistent with other languages.

docs(upperFirst): Update docs for `upperFirst`

---

docs/ja/reference/promise/withTimeout.md
docs/ko/reference/promise/withTimeout.md
docs/reference/promise/withTimeout.md
docs/zh_hans/reference/promise/withTimeout.md
src/promise/withTimeout.ts

I've updated the `withTimeout` example to improve understanding.

docs(fetchData): Improve example of `withTimeout`

---

src/compat/_internal/normalizeForCase.ts

I found a tiny spelling mistake of a comment.

docs(compat): fix a comment

---

docs/ja/reference/array/maxBy.md
docs/ja/reference/array/minBy.md
docs/ko/reference/array/maxBy.md
docs/ko/reference/array/minBy.md
docs/reference/array/maxBy.md
docs/reference/array/minBy.md
docs/zh_hans/reference/array/maxBy.md
docs/zh_hans/reference/array/minBy.md
src/array/maxBy.ts
src/array/minBy.ts

I found the maxBy and minBy utils quite useful, but noticed there weren't many examples. 
I thought that adding more examples might encourage developers to use these functions more frequently, 
so I've included some additional ones.
If this approach is helpful, I'd be glad to provide similar examples for other utils as well. 
Please let me know if you think this would benefit the project. 👍

docs: Add detail examples to docs in maxBy, minBy

---

docs/ko/reference/compat/array/castArray.md
docs/reference/compat/array/castArray.md

docs: fix castArray import paths

---

benchmarks/performance/isMap.bench.ts
docs/ko/reference/predicate/isMap.md
docs/reference/predicate/isMap.md
src/predicate/index.ts
src/predicate/isMap.spec.ts
src/predicate/isMap.ts

Hi there!
I add `isMap` function.

feat(isMap): add isMap

---

docs/ja/reference/predicate/isMap.md
docs/ja/reference/predicate/isSet.md
docs/zh_hans/reference/predicate/isMap.md
docs/zh_hans/reference/predicate/isSet.md

I append ja and zh_hans docs for `isSet` and `isMap` 👍 
- #596
- #600

docs(predicate): append docs fot `isSet` and `isMap`

---

benchmarks/performance/flowRight.bench.ts
docs/reference/function/flowRight.md
docs/zh_hans/reference/function/flowRight.md
src/function/flowRight.spec.ts
src/function/flowRight.ts
src/function/index.ts

feat(flowRight): implement flowRight

---

docs/ja/reference/compat/function/flip.md
docs/reference/compat/function/flip.md

i've made documentation consistent with other languages

docs(flip): Update docs for `flip`

---

docs/ja/reference/array/dropWhile.md
docs/ko/reference/array/dropWhile.md
docs/zh_hans/reference/array/dropWhile.md
src/compat/array/dropWhile.ts

Thanks for adding full compatibility in this [commit](https://github.com/toss/es-toolkit/commit/c0efc6536091aaf5774bffb9698378af52607ae7). I learned a lot from it. While reviewing, I noticed a missing part, so I added it.

docs(dropWhile): Update docs for `dropWhile`

---

docs/ja/reference/compat/array/filter.md
docs/ko/reference/compat/array/filter.md
docs/reference/compat/array/filter.md
docs/zh_hans/reference/compat/array/filter.md
src/compat/array/filter.spec.ts
src/compat/array/filter.ts

- I've fixed `filter` to provide correct arguments when it is used with object.
- Updated docs

fix(filter): Ensure `filter` provide correct arguments to the predicate function

---

benchmarks/performance/curryRight.bench.ts
docs/reference/function/curryRight.md
docs/zh_hans/reference/function/curry.md
docs/zh_hans/reference/function/curryRight.md
src/function/curryRight.spec.ts
src/function/curryRight.ts
src/function/index.ts

feat(curryRight): implement curryRight

---

docs/ko/reference/predicate/isJSONValue.md

- Updated korean translation of `boolean`

docs(isJSONValue): Update docs

---

docs/ja/reference/function/flow.md
docs/ko/reference/function/flow.md

- Added missing compatibility description to ko and ja docs

docs(flow): Update docs

---

docs/ja/reference/function/curryRight.md
docs/ko/reference/function/curryRight.md
docs/reference/function/curryRight.md
docs/zh_hans/reference/function/curryRight.md
src/function/curryRight.ts

- Updated parameter names for better understanding

docs(curryRight): Rename parameters for clarity and update docs

---

docs/ja/reference/function/flowRight.md
docs/ko/reference/function/flowRight.md

- Removed duplicated signature
- Added missing compatibility section

docs(flowRight): Update docs

---

benchmarks/performance/constant.bench.ts
src/compat/index.ts
src/compat/util/constant.spec.ts
src/compat/util/constant.ts

It is very simple function, but I implemented this as it frequently appears in compatibility test code.

feat(constant): add `constant` in compat layer

---

benchmarks/performance/dropRightWhile.bench.ts
benchmarks/performance/dropWhile.bench.ts
docs/ja/reference/array/dropRightWhile.md
docs/ko/reference/array/dropRightWhile.md
docs/reference/array/dropRightWhile.md
docs/zh_hans/reference/array/dropRightWhile.md
src/array/dropRightWhile.ts
src/array/dropWhile.ts
src/compat/array/dropRightWhile.spec.ts
src/compat/array/dropRightWhile.ts
src/compat/index.ts

feat(compat): implement dropRightWhile

---

src/compat/predicate/isEqualWith.spec.ts

fix(ci) : simple ci workflow error

---

src/compat/array/difference.spec.ts
src/compat/array/difference.ts

the document will be updated in https://github.com/toss/es-toolkit/pull/679

fix(difference): support array-like object

---

benchmarks/performance/isDate.bench.ts
src/compat/index.ts
src/compat/predicate/isDate.spec.ts
src/compat/predicate/isDate.ts

I added `isDate` in compat layer.

feat(compat): Add `isDate` in compat

---

src/compat/array/dropRightWhile.ts
src/compat/array/dropWhile.ts

docs: Update docs for `dropWhile` and `dropRightWhile`

---

docs/ja/reference/math/randomInt.md
docs/ko/reference/math/randomInt.md

Synchronized example of randomInt

docs(randomInt): Update docs

---

docs/ko/reference/predicate/isPlainObject.md

Synchronized Korean documentation example with other languages.

docs(isPlainObject): Update example of korean documentation

---

src/array/at.ts

fix(at): improve performance

---

benchmarks/performance/intersection.bench.ts
docs/ja/reference/array/intersection.md
docs/ko/reference/array/intersection.md
docs/reference/array/intersection.md
docs/zh_hans/reference/array/intersection.md
src/compat/_internal/stubNaN.ts
src/compat/array/intersection.spec.ts
src/compat/array/intersection.ts
src/compat/index.ts

I added the `intersection` function to the compatibility layer.

feat(intersection): Add `intersection` to compat layer

---

docs/ja/reference/compat/array/first.md
docs/reference/compat/array/first.md
docs/zh_hans/reference/compat/array/first.md

Updated example for the `first` function.

docs(first): Update example

---

src/array/differenceWith.spec.ts

added test cases.
First case is about object array.
Second case is for duplicate elements in a array.

test(differenceWith): add cases

---

docs/ja/reference/string/upperFirst.md

docs(upperFirst): fix typos

---

docs/ja/reference/compat/function/bindKey.md

docs(bindKey): translate text of Returns

---

docs/ja/reference/compat/predicate/isInteger.md
docs/ja/reference/predicate/isSymbol.md

docs(isSymbol, isInteger): fix typos

---

docs/ja/reference/function/spread.md

docs(spread): translate text of Returns

---

src/compat/predicate/isMatch.spec.ts
src/compat/predicate/isMatch.ts
tests/check-dist.spec.ts

close https://github.com/toss/es-toolkit/issues/750

fix(isMatch): should not ignore null

---

docs/ja/reference/object/merge.md
docs/ja/reference/object/toMerged.md
docs/ko/reference/object/merge.md
docs/ko/reference/object/toMerged.md
docs/reference/object/merge.md
docs/reference/object/toMerged.md
docs/zh_hans/reference/object/merge.md
docs/zh_hans/reference/object/toMerged.md
src/object/toMerged.ts

https://github.com/toss/es-toolkit/pull/740
Like `merge`, `toMerged` also changes the type.
It also modifies the documentation.

fix(toMerged): improved toMerged function types

---

benchmarks/performance/union.bench.ts
src/compat/array/union.spec.ts
src/compat/array/union.ts

I added `union` in compat layer
issue #772 
benchmark

feat(union): add `union` to compat layer

---

src/math/range.ts

We can simplify the implementation logic a bit more by setting `default parameters` for the `step`! 🤗

refactor(range): simplify the range function

---

src/math/rangeRight.ts

https://github.com/toss/es-toolkit/pull/781 This is the same thing !

refactor(rangeRight): simplify the rangeRight function

---

src/compat/index.ts

Add missing `union` export in `src/compat/index.ts`

fix(union): add missing union export

---

src/compat/array/uniqBy.spec.ts
src/compat/array/uniqBy.ts
src/compat/util/iteratee.ts

I found the earlier realization very strange

fix(compat/uniqBy): fix lodash compatibility

---

src/array/intersectionWith.spec.ts
src/array/intersectionWith.ts

fix(intersectionWith): first array and second array's types can different

---

benchmarks/package.json
benchmarks/performance/cloneDeep.bench.ts
yarn.lock

bench(cloneDeep): add rfdc

---

benchmarks/performance/toArray.bench.ts
docs/ko/reference/compat/util/toArray.md
docs/reference/compat/util/toArray.md
src/compat/index.ts
src/compat/util/toArray.spec.ts
src/compat/util/toArray.ts

I added toArray to compat layer
benchmarks

feat(toArray) : Add toArray to compat layer

---

benchmarks/bundle-size/add.spec.ts
benchmarks/bundle-size/chunk.spec.ts
benchmarks/bundle-size/clone.spec.ts
benchmarks/bundle-size/cloneDeep.spec.ts
benchmarks/bundle-size/curry.spec.ts
benchmarks/bundle-size/difference.spec.ts
benchmarks/bundle-size/escape.spec.ts
benchmarks/bundle-size/escapeRegExp.spec.ts
benchmarks/bundle-size/find.spec.ts
benchmarks/bundle-size/findKey.spec.ts
benchmarks/bundle-size/flow.spec.ts
benchmarks/bundle-size/isEqual.spec.ts
benchmarks/bundle-size/isPlainObject.spec.ts
benchmarks/bundle-size/mapKeys.spec.ts
benchmarks/bundle-size/mapValues.spec.ts
benchmarks/bundle-size/merge.spec.ts
benchmarks/bundle-size/mergeWith.spec.ts
benchmarks/bundle-size/omit.spec.ts
benchmarks/bundle-size/zip.spec.ts
benchmarks/bundle-size/zipObject.spec.ts
benchmarks/bundle-size/zipObjectDeep.spec.ts
benchmarks/bundle-size/zipWith.spec.ts

Hello. Thank you for creating such a great library. I've added a test code for bundlesize while analysing the library, thank you.

test(benchmarks): Enhance benchmarks for bundle size

---

benchmarks/performance/kebabCase.bench.ts
benchmarks/performance/slice.bench.ts
benchmarks/performance/snakeCase.bench.ts
src/compat/math/sum.ts
src/compat/math/sumBy.ts
src/compat/util/constant.spec.ts
src/function/throttle.spec.ts

What do you think about adding a [code spell checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) to the VSCode's recommended extensions?
I believe it could help prevent typos.

fix: correct typos

---

src/compat/index.ts

fix https://github.com/toss/es-toolkit/issues/899

fix(compat): restore removed export of uniqueId Function

---

benchmarks/performance/subtract.bench.ts
docs/ja/reference/math/subtract.md
docs/ko/reference/math/subtract.md
docs/reference/math/subtract.md
docs/zh_hans/reference/math/subtract.md
src/compat/index.ts
src/compat/math/subtract.spec.ts
src/compat/math/subtract.ts

#893
I added `subtract` to compat layer.

feat(subtract): Add `subtract` to compat layer

---

src/compat/predicate/isMatch.ts

Simplify condition check by returning keys.length === 0 directly.
I hope it helps!

fix(isMatch): simplify condition check

---

docs/ja/reference/compat/array/find.md
docs/ko/reference/compat/array/find.md
docs/reference/compat/array/find.md
docs/zh_hans/reference/compat/array/find.md
src/compat/array/find.spec.ts
src/compat/array/find.ts

fix(find): add support for fromIndex parameter

---

docs/ja/reference/function/retry.md
docs/ko/reference/function/retry.md
docs/reference/function/retry.md
docs/zh_hans/reference/function/retry.md
src/function/index.ts
src/function/retry.spec.ts
src/function/retry.ts

feat(retry): add retry

---

src/compat/math/multiply.spec.ts

Thanks for adding the logic I missed in #930! 
I found a duplicate test and deleted it.

test(multiply): remove duplicate test

---

docs/ja/reference/string/reverseString.md
docs/ko/reference/string/reverseString.md
docs/reference/string/reverseString.md
docs/zh_hans/reference/string/reverseString.md
src/string/reverseString.ts

I accidentally wrote the comment Example incorrectly, so I'll fix it.

fix(reverseString): fix comment and docs

---

README-ko_kr.md

Add Example section that is missing content from the Korean README file.

docs(README): add missing content

---

src/array/at.ts

- return type of `at` function is `T[]`, but in comments it was a `Array<T | undefined>`.

chore(at): fix return type in comments

---

src/compat/string/words.spec.ts
src/compat/string/words.ts

close https://github.com/toss/es-toolkit/issues/1053

fix(words): support ordinal number/contractions

---

benchmarks/performance/sortedLastIndexOf.bench.ts
docs/ja/reference/compat/array/sortedLastIndexOf.md
docs/ko/reference/compat/array/sortedLastIndexOf.md
docs/reference/compat/array/sortedLastIndexOf.md
docs/zh_hans/reference/compat/array/sortedLastIndexOf.md
src/compat/array/sortedLastIndexOf.spec.ts
src/compat/array/sortedLastIndexOf.ts
src/compat/compat.ts

feat(compat): sortedLastIndexOf

---

benchmarks/performance/memoize.bench.ts
docs/ja/reference/compat/function/memoize.md
docs/ko/reference/compat/function/memoize.md
docs/reference/compat/function/memoize.md
docs/zh_hans/reference/compat/function/memoize.md
src/compat/compat.ts
src/compat/function/memoize.spec.ts
src/compat/function/memoize.ts

I've tried to modify it using class syntax. Is this the right approach?
closed: #1012

feat(memoize): add memoize to compat

---

docs/ja/reference/compat/function/wrap.md
docs/ja/reference/compat/object/result.md
docs/ko/reference/compat/function/wrap.md
docs/ko/reference/compat/object/result.md
docs/reference/compat/function/wrap.md
docs/reference/compat/object/result.md
docs/zh_hans/reference/compat/function/wrap.md
docs/zh_hans/reference/compat/object/result.md

I just ran a 'format' script 🙇 
you can close this pr, so please feel free to check it 👍

docs(wrap, result): run format script

---

docs/ko/reference/compat/util/toNumber.md

docs(toNumber): remove meaningless string

---

.github/CONTRIBUTING.md
src/array/maxBy.spec.ts
src/array/maxBy.ts
src/array/minBy.spec.ts
src/array/minBy.ts

Improved the type definitions and implementation of `maxBy` and `minBy` functions:
1. Added explicit empty array handling logic
2. Enhanced consistency of code logic
3. Updated comments and added examples
4. Optimized performance (changed loop starting point)
The existing `maxBy` and `minBy` functions were declared in the type system to potentially return `undefined` for empty arrays, but the code did not explicitly handle this case. Test cases already expected `undefined` to be returned for empty arrays.
This PR enhances consistency between code and type definitions and clarifies empty array handling logic, improving maintainability.
- `src/array/maxBy.ts`
- `src/array/minBy.ts`
All existing tests continue to pass. Additional tests for handling NaN values have been added.
```bash
yarn …
```

fix[maxBy, minBy]: improve type definitions and empty array handling

---

benchmarks/performance/findKey.bench.ts
benchmarks/performance/findLastKey.bench.ts
benchmarks/performance/identity.bench.ts
benchmarks/performance/includes.bench.ts
benchmarks/performance/invertBy.bench.ts
benchmarks/performance/uniqueId.bench.ts

- Improved benchmark performance by removing import overhead

chore : remove bench import overhead

---

src/function/once.ts

docs(once): improved once function jsDoc

---

src/compat/array/unzipWith.ts
src/compat/math/minBy.ts

chore: fix typos

---

docs/ko/reference/compat/math/multiply.md

docs(multiply): fix typo

---

src/compat/object/cloneDeepWith.spec.ts
src/compat/object/cloneDeepWith.ts
src/object/cloneDeepWith.spec.ts
src/object/cloneDeepWith.ts

fix(cloneDeepWith): Handle customizer returning null

---

src/compat/object/findKey.spec.ts
src/compat/object/findLastKey.spec.ts

test(compat/object/{findKey,findLastKey}): add test cases for default parameters

---

src/compat/math/maxBy.spec.ts
src/compat/math/meanBy.spec.ts
src/compat/math/minBy.spec.ts

test(compat/math/{maxBy,meanBy,minBy}): add test cases for default parameters

---

src/compat/array/dropWhile.spec.ts

test(compat/array/dropWhile): add test case for 'identity' function default 'predicate'

---

src/compat/array/pullAllWith.spec.ts

test(compat/array/pullAllWith): add test case for array-like values parameter

---

src/compat/array/forEachRight.spec.ts

test(compat/array/forEachRight): add test case for 'identity' function default callback

---

src/compat/array/findLastIndex.spec.ts

test(compat/array/findLastIndex): add test case for 'identity' function default 'predicate'
